"""Bake the shared assessment library's latest bundles into DEEP's data/ registry.

The 8 state-SQT assessments come from ``build_deep_data.py`` (resolved out of the STAF
metric library). This script folds in the completed assessments published to
``apps/library/`` so the *cloud* DEEP — which does not ship ``apps/library`` — still lists
them. Every version DEEP shows (a draft, preliminary or certified one whose Show in DEEP is
on) of every DEEP assessment is baked, each as ``bundles/<id>@v<N>.deep.json``, and the
default version (the newest Final, else Preliminary, else Draft one) is written again as
``bundles/<id>.deep.json``; hidden versions, versions under review, and revised or retired
versions stay in the library only. Idempotent: re-running with the same library yields the
same output.

It also copies each baked version's Excel calculator (generated by StreamCurves at
publish and recorded in the assessment's ``artifacts.json``) into
``www/calculators/<id>@v<N>.xlsx``, with ``<id>.xlsx`` for the default version and an
``index.json`` DEEP reads to match a workbook to the bundle it was built from. A copy
only: this script stays pure stdlib, so it never builds a workbook.

A bake of DEEP's own folders then rewrites the STAF site's calculator list
(``docs/_data/deep_calculators.json``, ``scripts/build_site_calculators.py``), which the site's
Apply STAF page offers for download.

Run it after publishing a library version, then commit ``apps/deep/data/``,
``apps/deep/www/calculators/`` and ``docs/_data/deep_calculators.json``. StreamCurves' publish
action runs it automatically on local/desktop.

Usage:
    py scripts/bake_library_into_deep.py [--out data] [--library-root PATH] [--default-only]

``--default-only`` bakes each assessment's default version instead of every eligible version,
for a smaller deploy; the remote library keeps serving every eligible version to the version
chooser. Without the flag nothing changes: every eligible version bakes.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path

DEEP_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = DEEP_ROOT / "data"
DEFAULT_WWW = DEEP_ROOT / "www" / "calculators"
SITE_LIST = Path(__file__).resolve().with_name("build_site_calculators.py")

if str(DEEP_ROOT) not in sys.path:
    sys.path.insert(0, str(DEEP_ROOT))
from deep import library as deep_library  # noqa: E402


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path: Path, obj) -> None:
    # LF on every platform, as git stores it (a Windows bake used to leave CRLF copies)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False), encoding="utf-8",
                    newline="\n")


def bake(out: Path | None = None, library_root: Path | None = None,
         www: Path | None = None, *, default_only: bool = False) -> dict:
    """Rewrite ``deep-assessments.json`` (v2) authoritatively from the shared library.

    The registry becomes ``{schemaVersion: 2, tier, libraryCatalog, assessments}`` where
    ``assessments`` carries **one record per eligible (id, version)** (draft, preliminary or
    certified, and shown), each stamped ``assessmentRef``/``version``/``lifecycle``.
    Per-version bundle files ``bundles/<id>@v<N>.deep.json`` plus a default
    ``bundles/<id>.deep.json`` are written; stale bundle files are removed. ``libraryCatalog``
    holds each assessment's pointers over those versions (:func:`deep.library.default_pointers`:
    the newest Final version is the default, else the newest Preliminary one, else the newest
    Draft), so an assessment DEEP shows no version of has no pointer, no default bundle and no
    calculator. Ordering is deterministic (id, then version). Idempotent: same library -> same
    output.

    ``default_only`` keeps one record per assessment, its ``defaultVersion``; the other
    eligible versions stay in the library (and on the remote library, which the version
    chooser reads) and are not baked. ``libraryCatalog`` still lists every pointer.

    Returns a summary dict: ``assessments`` (id list), ``records`` (count),
    ``libraryCount`` (every eligible version in the library, baked or not), ``defaultOnly``,
    and ``calculators`` (``copied`` and ``missing`` refs, see :func:`bake_calculators`).
    ``www`` is the calculators folder (default: the ``www/calculators`` sibling of ``out``).
    """
    out = Path(out) if out else DEFAULT_OUT
    if library_root is not None:
        os.environ["STAF_LIBRARY_ROOT"] = str(library_root)

    bundles = deep_library.all_eligible_bundles()
    pointers = deep_library.default_pointers(bundles)
    default_version = {aid: p.get("defaultVersion") for aid, p in pointers.items()}

    # Deterministic ordering: by assessmentId, then version.
    records = sorted(bundles, key=lambda b: (b.get("assessmentId") or "", int(b.get("version") or 0)))
    if default_only:
        records = [b for b in records
                   if int(b.get("version") or 0) == default_version.get(b.get("assessmentId"))]
    library_catalog = {aid: pointers[aid] for aid in sorted(pointers)}

    doc = {
        "schemaVersion": 2,
        "tier": "detailed",
        "generatedFrom": "apps/library",
        "libraryCatalog": library_catalog,
        "assessments": records,
    }
    reg_path = out / "deep-assessments.json"
    _write(reg_path, doc)

    # Rewrite bundles/: clear stale .deep.json, then write per-version + default copies.
    bundles_dir = out / "bundles"
    if bundles_dir.is_dir():
        for old in bundles_dir.glob("*.deep.json"):
            old.unlink()
    for bundle in records:
        aid = bundle.get("assessmentId")
        ver = int(bundle.get("version") or 0)
        if not aid or ver < 1:
            continue
        payload = {"schemaVersion": 1, "tier": "detailed", **bundle}
        _write(bundles_dir / f"{aid}@v{ver}.deep.json", payload)
        if ver == default_version.get(aid):
            _write(bundles_dir / f"{aid}.deep.json", payload)

    calculators = bake_calculators(
        records, default_version,
        Path(www) if www is not None else out.parent / "www" / "calculators")

    assessment_ids = sorted({b.get("assessmentId") for b in records if b.get("assessmentId")})
    return {
        "assessments": assessment_ids,
        "records": len(records),
        "libraryCount": len(bundles),
        "defaultOnly": bool(default_only),
        "calculators": calculators,
    }


CALCULATOR_KIND = "excel-calculator"
CALCULATOR_FILE = "calculator.xlsx"


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _calculator_record(assessment_dir: Path, version: int) -> dict | None:
    """The current ``excel-calculator`` record of a version in the assessment's
    append-only ``artifacts.json`` (the last record wins), or None."""
    path = assessment_dir / "artifacts.json"
    if not path.is_file():
        return None
    found = None
    for rec in (_load(path).get("history") or []):
        try:
            same = int(rec.get("version")) == int(version) and rec.get("kind") == CALCULATOR_KIND
        except (TypeError, ValueError):
            same = False
        if same:
            found = rec
    return found


def bake_calculators(records: list[dict], default_version: dict, dest: Path) -> dict:
    """Copy every baked version's Excel calculator into ``dest`` and write its index.

    A workbook is copied only when the library records it, the file on disk has the
    recorded hash, and it was built from the very content being baked (its recorded
    ``contentDigest`` equals the bundle's). Anything else is listed as missing, so a
    calculator built for other curves is never shipped as this version's. The folder
    is rewritten from scratch each time (its own stale sweep) and ``index.json`` has
    no timestamp, so the same library gives the same bytes.

    Returns ``{"copied": [ref...], "missing": [ref...]}``.
    """
    dest = Path(dest)
    if dest.is_dir():
        for old in list(dest.glob("*.xlsx")) + list(dest.glob("index.json")):
            old.unlink()
    root = deep_library.library_root()
    index: dict[str, dict] = {}
    defaults: dict[str, str] = {}
    copied, missing = [], []
    for bundle in records:
        aid = bundle.get("assessmentId")
        ver = int(bundle.get("version") or 0)
        if not aid or ver < 1:
            continue
        ref = f"{aid}@v{ver}"
        adir = root / "assessments" / str(aid)
        src = adir / f"v{ver}" / CALCULATOR_FILE
        rec = _calculator_record(adir, ver)
        ok = (rec is not None and src.is_file() and _sha256(src) == rec.get("sha256")
              and rec.get("contentDigest") == bundle.get("contentDigest"))
        if not ok:
            missing.append(ref)
            continue
        dest.mkdir(parents=True, exist_ok=True)
        name = f"{ref}.xlsx"
        shutil.copyfile(src, dest / name)
        index[ref] = {"file": name, "sha256": rec.get("sha256"), "bytes": rec.get("bytes"),
                      "contentDigest": rec.get("contentDigest"),
                      "generatorVersion": rec.get("generatorVersion")}
        copied.append(ref)
        if ver == default_version.get(aid):
            shutil.copyfile(src, dest / f"{aid}.xlsx")
            defaults[str(aid)] = f"{aid}.xlsx"
    if index:
        _write(dest / "index.json", {"schemaVersion": 1,
                                     "calculators": {k: index[k] for k in sorted(index)},
                                     "default": {k: defaults[k] for k in sorted(defaults)}})
    return {"copied": copied, "missing": missing}


def refresh_site_list(out, www) -> str | None:
    """After a bake of DEEP's own folders, rewrite the STAF site's calculator list
    (``docs/_data/deep_calculators.json``) so the Apply STAF page follows every publish. None
    when the bake wrote elsewhere (tests, a scratch folder). Never raises: the bake itself
    succeeded, and ``tests/test_site_calculators.py`` catches a stale list."""
    if Path(out).resolve() != DEFAULT_OUT.resolve():
        return None
    if www is not None and Path(www).resolve() != DEFAULT_WWW.resolve():
        return None
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("build_site_calculators", SITE_LIST)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module.write()
    except Exception as exc:  # noqa: BLE001 - reported, never fatal
        return f"site calculators not updated ({type(exc).__name__}: {exc})"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Bake apps/library/ latest bundles into DEEP's data/ registry."
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="DEEP data/ directory.")
    parser.add_argument(
        "--library-root",
        type=Path,
        default=None,
        help="Override the library root (default: the apps/library sibling).",
    )
    parser.add_argument("--www", type=Path, default=None,
                        help="Calculators folder (default: www/calculators beside --out).")
    parser.add_argument("--default-only", action="store_true",
                        help="Bake each assessment's default version only (its newest Final, "
                             "else Preliminary, else Draft version); every eligible version "
                             "is baked otherwise.")
    args = parser.parse_args(argv)
    result = bake(out=args.out, library_root=args.library_root, www=args.www,
                  default_only=args.default_only)
    print(
        f"Baked {result['records']} version record(s) from "
        f"{len(result['assessments'])} assessment(s) into "
        f"{args.out / 'deep-assessments.json'}"
        + (f" (default versions only; the library holds {result['libraryCount']} eligible)"
           if args.default_only else "")
    )
    if result["assessments"]:
        print(f"  assessments: {', '.join(result['assessments'])}")
    calc = result.get("calculators") or {}
    print(f"  calculators: {len(calc.get('copied') or [])} copied"
          + (f", none recorded for {', '.join(calc['missing'])}" if calc.get("missing") else ""))
    site = refresh_site_list(args.out, args.www)
    if site:
        print(f"  {site}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
