"""The EASI Excel calculator, served blank from the report.

The workbook under ``www/calculator/`` is generated by ``scripts/build_calculator.py``
from the same scoring definitions the application uses (catalog, reference
curves, weights, anchors). It is a deliverable of the methodology, so this
module only hands the committed bytes out; nothing is written at runtime.
``tests/test_calculator_parity.py`` proves the workbook scores like the engine.
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path

#: The committed calculator. Part of the filename so a returned workbook can be
#: traced to the release it came from.
TEMPLATE_VERSION = "1.0.0"

TEMPLATE_PATH = (Path(__file__).resolve().parent.parent
                 / "www" / "calculator" / f"EASI_Calculator_{TEMPLATE_VERSION}.xlsx")


@lru_cache(maxsize=1)
def blank_bytes() -> bytes:
    """The committed workbook, read once."""
    return TEMPLATE_PATH.read_bytes()


def blank_filename() -> str:
    return TEMPLATE_PATH.name
