"""Static configuration and data loaders for EASI.

Holds (a) constants that mirror the STAF screening methodology (rating index
midpoints, outcome weights, color bands) and (b) the per-metric *automation
registry* describing how each EASI metric is computed from national data,
its data-confidence, and whether it is overrideable. STAF-derived facts
(criteria, thresholds, function mapping) live in ``data/easi-metrics.json``;
this module holds the app's design metadata and loaders.
"""
from __future__ import annotations

import functools
import json
import os
from pathlib import Path


def _resolve_data_dir() -> Path:
    """Resolve the bundled data dir, portable across repo and vendored layouts.

    Order: ``EASI_DATA_DIR`` env override -> an in-package ``easi/data`` (used when
    the ``easi`` package is vendored into another app without a sibling ``data/``)
    -> the repo layout's sibling ``apps/easi/data`` (``parents[1]/data``).
    """
    env = os.environ.get("EASI_DATA_DIR")
    if env:
        return Path(env)
    in_pkg = Path(__file__).resolve().parent / "data"
    if in_pkg.is_dir():
        return in_pkg
    return Path(__file__).resolve().parents[1] / "data"


DATA_DIR = _resolve_data_dir()

# --- STAF scoring constants ---
# rating -> index (0-1): the midpoint of each STAF condition band
# (Functioning 0.70-1.0, Functioning-at-Risk 0.40-0.69, Non-Functioning 0-0.39)
RATING_INDEX: dict[str, float] = {"Good": 0.85, "Fair": 0.545, "Poor": 0.195}
RATINGS = ("Good", "Fair", "Poor")

# CWA outcome contribution weights: Direct, indirect, none
WEIGHTS: dict[str, float] = {"D": 1.0, "i": 0.1, "-": 0.0}
OUTCOMES = ("physical", "chemical", "biological")

FUNCTION_SCORE_MAX = 15

# Color bands (hex mirrors STAF). Index bands (0-1) and function-score bands (0-15).
INDEX_BANDS = [(0.39, "#f5b5b5"), (0.69, "#f5e7a6"), (1.01, "#c8d9f2")]
INDEX_BAND_LABELS = ("Non-Functioning", "Functioning-at-Risk", "Functioning")  # condition category per band (aligned with INDEX_BANDS)
FUNCTION_SCORE_BANDS = [(5, "#f5b5b5"), (10, "#f5e7a6"), (FUNCTION_SCORE_MAX, "#c8d9f2")]
# Short F/AR/NF condition codes per function-score band (aligned with FUNCTION_SCORE_BANDS);
# used for the optional badge next to a function score (STAF "Show F/AR/NF labels").
FUNCTION_SCORE_BAND_SHORT = ("NF", "AR", "F")

# Data-confidence levels for the report badges
CONFIDENCE = ("H", "M", "M/L", "L")


@functools.lru_cache(maxsize=None)
def _load(name: str):
    return json.loads((DATA_DIR / name).read_text(encoding="utf-8"))


def cwa_mapping() -> dict[str, dict[str, str]]:
    """function id -> {physical, chemical, biological} contribution codes."""
    rows = _load("cwa-mapping.json")
    return {r["id"]: {k: r[k] for k in OUTCOMES} for r in rows}


def functions() -> list[dict]:
    return _load("functions.json")


def easi_metrics() -> dict:
    return _load("easi-metrics.json")


def metrics_by_id() -> dict[str, dict]:
    return {m["metricId"]: m for m in easi_metrics()["metrics"]}


def screening_methods() -> dict:
    """The canonical automated screening-method catalog.

    ``data/screening-methods.json`` is the single source of truth for the automated
    formulas, exact Good/Fair/Poor boundaries, source hierarchy, and method provenance.
    :mod:`easi.screening_methods` evaluates it and :mod:`easi.methods` renders it, so the
    displayed criteria cannot drift from what actually produced the rating.
    """
    return _load("screening-methods.json")


def criteria_bands(mid: str, indicator: str | None = None) -> dict:
    """Good/Fair/Poor criteria strings for a metric, indicator-aware.

    Automated criteria come from the screening-method catalog so the displayed
    breakpoints are generated by the same band objects the evaluator used. ``indicator``
    selects one input of a worst-of method (e.g. the land-cover metric's ``impervious``
    vs ``agriculture``). Falls back to the generic STAF field prose in
    ``easi-metrics.json`` for anything the catalog does not describe numerically.
    """
    from . import screening_methods as sm

    try:
        method = sm.method_for(mid)
    except KeyError:
        method = None
    if method is not None:
        auto = sm.criteria_for(method).get("automated") or []
        if auto:
            block = next((a for a in auto if a["input"] == indicator), auto[0])
            bands = block.get("bands") or {}
            if bands:
                return {r: bands[r] for r in RATINGS if bands.get(r)}
    return metrics_by_id().get(mid, {}).get("criteria") or {}


# --- Per-metric automation registry (verified plan; keyed by metricId) ---
# scale: 'W' watershed, 'R' reach, 'W/R' both
# confidence: H / M / M/L / L   |   proxy/overrideable: bool
# datasource: short adapter key string for the metric's source pipeline
METRIC_REGISTRY: dict[str, dict] = {
    "catchment-hydrology-impervious-surface-cover": {
        "scale": "W", "confidence": "H", "proxy": False, "overrideable": False,
        "datasource": "streamcat:pctimp2019+pctcrop2019+pcthay2019"},
    "surface-water-storage-percent-wetlands-in-watershed": {
        "scale": "W", "confidence": "H", "proxy": False, "overrideable": False,
        "datasource": "streamcat:pctwdwet2019+pcthbwet2019"},
    "reach-inflow-concentrated-runoff-stormwater-inputs": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "proxy:streamcat:rddens"},
    "streamflow-regime-flow-alteration-regulation-water-use": {
        "scale": "W/R", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "streamcat:damnrmstor+runoff"},
    "low-flow-and-baseflow-dynamics-low-flow-wetted-connectivity": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "nrsa:pct_dr|streamcat:hyd"},
    "high-flow-dynamics-floodplain-engagement-frequency-bankfull-recurrence": {
        "scale": "R", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "threedep:bhr+bieger_bankfull"},
    "floodplain-connectivity-floodplain-access-entrenchment": {
        "scale": "R", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "threedep:entrenchment"},
    "hyporheic-connectivity-hyporheic-exchange-indicators": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "nhdplus:slope (sinuosity context)"},
    "channel-evolution-channel-evolution-stage-and-trends": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "threedep:bhr+er|nhd_fcode|observed"},
    "channel-and-floodplain-dynamics-bank-erosion-and-armoring-condition": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "threedep:bhr|observed"},
    "sediment-continuity-sediment-supply-potential-watershed-banks": {
        "scale": "W", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "streamcat:pctcrop2019+pcthay2019,kffact,rddens"},
    "bed-composition-and-large-wood-substrate-condition-grain-size-embeddedness-fines-consolidation": {
        "scale": "R", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "nrsa:xembed|streamcat:sed"},
    "light-and-thermal-regime-stream-temperature": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "streamcat:rp100_woody+pctimp2019 (wqp temp context)"},
    "carbon-processing-detrital-processing-cpom-retention-shredders": {
        "scale": "R", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "streamcat:rp100_natural_veg"},
    "nutrient-cycling-nitrogen-and-phosphorus-concentrations": {
        "scale": "R/W", "confidence": "M/L", "proxy": True, "overrideable": True,
        "datasource": "wqp:tn_tp vs nrsa_benchmarks|streamcat:chem"},
    "water-and-soil-quality-regulatory-impairment-status-305b-303d-tmdl": {
        "scale": "R", "confidence": "H", "proxy": False, "overrideable": True,
        "datasource": "attains|streamcat:chem"},
    "habitat-provision-in-stream-habitat-complexity-and-cover": {
        "scale": "R", "confidence": "L", "proxy": True, "overrideable": True,
        "datasource": "streamcat:rp100_woody (sinuosity context)"},
    "population-support-biological-integrity-ibi-community-condition": {
        "scale": "R", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "nrsa_class|streamcat:prg_bmmi|ici_iwi"},
    "community-dynamics-invasive-non-native-species-presence": {
        "scale": "W", "confidence": "M", "proxy": True, "overrideable": True,
        "datasource": "nas_by_huc12|huc8"},
    "watershed-connectivity-fish-passage-and-barrier-effects-longitudinal-connectivity": {
        "scale": "R", "confidence": "H", "proxy": False, "overrideable": False,
        "datasource": "nid_within_1mi"},
}


# Concise, plain-language definition of each metric (what it measures), shown in the
# report's ⓘ tooltip above the calculation method and scoring criteria. Curated here so
# the STAF source data stays untouched; keep one short sentence per metric.
METRIC_DEFINITIONS: dict[str, str] = {
    "catchment-hydrology-impervious-surface-cover":
        "Watershed land-cover pressure on catchment hydrology. Scored automatically on the more "
        "limiting of two indicators: impervious cover (speeds runoff) or agricultural cover "
        "(where farming, not pavement, is the dominant hydrologic alteration).",
    "surface-water-storage-percent-wetlands-in-watershed":
        "Share of the watershed that is wetland, which stores water, buffers peak flows, and "
        "sustains baseflow.",
    "reach-inflow-concentrated-runoff-stormwater-inputs":
        "Road density in the watershed, a stand-in for concentrated runoff pressure. It does "
        "not count actual outfalls or crossings.",
    "streamflow-regime-flow-alteration-regulation-water-use":
        "Degree of regulation: upstream reservoir storage relative to the river's annual runoff "
        "volume. It does not account for how dams are operated or for diversions.",
    "low-flow-and-baseflow-dynamics-low-flow-wetted-connectivity":
        "Whether the channel stays wetted and longitudinally connected during low-flow periods "
        "(flow permanence).",
    "high-flow-dynamics-floodplain-engagement-frequency-bankfull-recurrence":
        "How readily high flows reach the floodplain, from the bank-height ratio rather than a "
        "modeled recurrence interval.",
    "floodplain-connectivity-floodplain-access-entrenchment":
        "Whether the channel has lateral access to a floodplain, via the entrenchment ratio "
        "(floodprone width ÷ bankfull width).",
    "hyporheic-connectivity-hyporheic-exchange-indicators":
        "Potential for surface water to exchange with the shallow subsurface (hyporheic zone), "
        "screened from channel slope. Sinuosity is shown for context and is not rated.",
    "channel-evolution-channel-evolution-stage-and-trends":
        "Whether the channel is stable or actively incising/widening, its stage in the "
        "channel-evolution sequence.",
    "channel-and-floodplain-dynamics-bank-erosion-and-armoring-condition":
        "Susceptibility to bank erosion, from the bank-height ratio unless bank observations "
        "are entered. The proxy does not detect existing armoring.",
    "sediment-continuity-sediment-supply-potential-watershed-banks":
        "Potential for excess sediment from watershed sources, scored on the most limiting of "
        "agricultural cover, soil erodibility, and road density. Bank-derived supply is not "
        "represented.",
    "bed-composition-and-large-wood-substrate-condition-grain-size-embeddedness-fines-consolidation":
        "Quality of the streambed substrate (grain size, embeddedness, fines) that supports "
        "habitat and spawning.",
    "light-and-thermal-regime-stream-temperature":
        "Vulnerability to warming, scored on the more limiting of woody riparian shade and "
        "watershed impervious cover. It does not estimate stream temperature.",
    "carbon-processing-detrital-processing-cpom-retention-shredders":
        "Potential supply of organic matter from riparian vegetation (forest, shrub, grassland, "
        "and wetland combined). It does not measure litter retention or shredder populations.",
    "nutrient-cycling-nitrogen-and-phosphorus-concentrations":
        "Whether nutrient (N and P) concentrations stay near reference levels rather than "
        "driving enrichment.",
    "water-and-soil-quality-regulatory-impairment-status-305b-303d-tmdl":
        "Whether the reach is on a Clean Water Act impaired-waters list (303(d)/305(b)/TMDL) "
        "for water-quality problems.",
    "habitat-provision-in-stream-habitat-complexity-and-cover":
        "Woody riparian corridor cover as a stand-in for habitat support (cover, wood "
        "recruitment, bank structure). It is not a field inventory of pools, wood, or bedforms. "
        "Sinuosity is shown for context.",
    "population-support-biological-integrity-ibi-community-condition":
        "Condition of the aquatic community, from measured benthic or fish results where "
        "available, otherwise a labeled model or landscape-integrity estimate.",
    "community-dynamics-invasive-non-native-species-presence":
        "Extent to which invasive or non-native species are present in the watershed and may "
        "displace natives.",
    "watershed-connectivity-fish-passage-and-barrier-effects-longitudinal-connectivity":
        "Mapped dams within a mile of the reach, as a sign of possible barriers to fish "
        "movement. Proximity alone does not establish whether a barrier is passable.",
}

# Short note on how each metric's value is computed, shown in the report ⓘ tooltip's
# Calculation section (the data Source is shown separately). Most screening metrics bin a
# dataset value directly, so only metrics with an extra computation or a composite/derived
# input are listed here; the rest fall back to the "used directly" default in the app.
METRIC_CALCULATIONS: dict[str, str] = {
    "reach-inflow-concentrated-runoff-stormwater-inputs":
        "From watershed road density, a directional proxy. It does not count outfalls "
        "or road-stream crossings.",
    "streamflow-regime-flow-alteration-regulation-water-use":
        "Degree of regulation = upstream normalized storage relative to the annual runoff "
        "volume.",
    "low-flow-and-baseflow-dynamics-low-flow-wetted-connectivity":
        "From the NRSA wetted-channel observation where connected evidence qualifies, otherwise "
        "the StreamCat HYD integrity fallback.",
    "high-flow-dynamics-floodplain-engagement-frequency-bankfull-recurrence":
        "From the bank-height ratio (low-bank height ÷ maximum bankfull depth).",
    "floodplain-connectivity-floodplain-access-entrenchment":
        "Entrenchment ratio = flood-prone width ÷ bankfull width.",
    "hyporheic-connectivity-hyporheic-exchange-indicators":
        "Channel slope binned to a rating. Sinuosity is displayed as context.",
    "channel-evolution-channel-evolution-stage-and-trends":
        "Worse of the bank-height and entrenchment ratios. A canal or ditch classification "
        "rates Poor directly.",
    "channel-and-floodplain-dynamics-bank-erosion-and-armoring-condition":
        "From the bank-height ratio unless observed bank condition is entered.",
    "sediment-continuity-sediment-supply-potential-watershed-banks":
        "Most limiting of agricultural cover, soil K-factor, and road density.",
    "habitat-provision-in-stream-habitat-complexity-and-cover":
        "Woody riparian corridor cover binned to a rating. Sinuosity is displayed as context.",
    "carbon-processing-detrital-processing-cpom-retention-shredders":
        "Percent of the 100 m riparian buffer in natural vegetation (forest + shrub + grassland "
        "+ wetland).",
    "water-and-soil-quality-regulatory-impairment-status-305b-303d-tmdl":
        "From the reach's Clean Water Act impaired-waters listing (303(d)/305(b)/TMDL).",
    "watershed-connectivity-fish-passage-and-barrier-effects-longitudinal-connectivity":
        "From dam/barrier presence affecting upstream-downstream passage.",
}


def validate_registry() -> list[str]:
    """Return a list of consistency problems between registry and metric data."""
    problems: list[str] = []
    metric_ids = set(metrics_by_id())
    reg_ids = set(METRIC_REGISTRY)
    for mid in metric_ids - reg_ids:
        problems.append(f"metric {mid} missing from METRIC_REGISTRY")
    for mid in reg_ids - metric_ids:
        problems.append(f"registry id {mid} not in easi-metrics.json")
    for mid in reg_ids - set(METRIC_DEFINITIONS):
        problems.append(f"metric {mid} missing from METRIC_DEFINITIONS")
    mapping = cwa_mapping()
    for m in easi_metrics()["metrics"]:
        if m["functionId"] not in mapping:
            problems.append(f"functionId {m['functionId']} not in cwa-mapping")
    return problems
