"""Concise wording for the method text DEEP shows for a metric (2026-10-04).

Published assessments carry each metric's measurement text in their hashed content
(``methodContext``, or ``howToMeasure`` in older versions), so the shorter wording is
applied here, at display, keyed by the exact published text. No bundle or digest
changes. :func:`deep.field_form.method_text` applies it, and that one function feeds
the Get Forms table, the field forms and metrics PDFs, and the metric's (i) on the
worksheet.

Each concise text keeps every number, unit, count, instrument and formula of the
published one. Only repetition goes, along with the engine name and version: the F/D
and Source columns already say a desktop metric is computed by DEEP. Text not listed
here is shown as published. The old and new pairs are listed for review in
``notes/2026-10-04_DEEP_Assessment_Page/method_text_review.md``.
"""
from __future__ import annotations

#: published text (whitespace collapsed) -> concise text
CONCISE: dict[str, str] = {
    "Bank height ratio at a representative riffle of the assessment reach: the height of the lower top of bank above the thalweg divided by the maximum bankfull depth (the stream quantification tools' field procedure, after Rosgen 2006). Measure it in the field; DEEP offers a DEM-derived value only where the cross sections pass the quality checks, and leaves the function unassessed until a value is entered.":
        "At a representative riffle, divide the height of the lower top of bank above the thalweg by the maximum bankfull depth (stream quantification tool procedure, after Rosgen 2006). Measure it in the field: DEEP offers a DEM value only where its cross sections pass the quality checks, and the function stays unassessed until a value is entered.",
    "Collect one D-frame net sample (500 micrometer mesh) one meter downstream of each of the 11 transects at the assigned left, center or right station, and composite them. A laboratory identifies a fixed count subsample. The value is the number of mayfly, stonefly and caddisfly taxa.":
        "Take a D-frame net sample (500 µm mesh) 1 m downstream of each of the 11 transects at the assigned left, center or right station, and composite them. A lab identifies a fixed-count subsample. Value: number of mayfly, stonefly and caddisfly taxa.",
    "From the same 11-transect composite D-frame net sample (500 micrometer mesh) and laboratory subsample. The value is the Shannon diversity of the taxa counted.":
        "From the 11-transect composite D-frame sample (500 µm mesh) and its lab subsample. Value: Shannon diversity of the taxa counted.",
    "Computed, not read in the field. From the 11-transect composite D-frame net sample (500 micrometer mesh) and its fixed count laboratory subsample, score EPA's six regional benthic metrics with the published floor and ceiling values and rescale the sum to 0 to 100, as the 2018-19 technical support document describes.":
        "Computed: from the 11-transect composite D-frame sample (500 µm mesh) and its fixed-count lab subsample, score EPA's 6 regional benthic metrics against the published floors and ceilings and rescale the sum to 0 to 100 (NRSA 2018-19 technical support document).",
    "From the same 11-transect composite D-frame net sample (500 micrometer mesh) and laboratory subsample. The value is the percent of individuals that belong to pollution tolerant taxa.":
        "From the 11-transect composite D-frame sample (500 µm mesh) and its lab subsample. Value: percent of individuals in pollution-tolerant taxa.",
    "From the same 11-transect composite D-frame net sample (500 micrometer mesh) and laboratory subsample. The value is the total number of taxa.":
        "From the 11-transect composite D-frame sample (500 µm mesh) and its lab subsample. Value: total number of taxa.",
    "Base flow index of the watershed, the percent of streamflow that comes from base flow (USGS base flow index grid). DEEP reads it from EPA StreamCat for the reach. Nothing is measured in the field.":
        "Percent of streamflow that comes from base flow in the watershed (USGS base flow index grid), read from EPA StreamCat for the reach. No field measurement.",
    "Chlorophyll a of the water column in micrograms per liter, from a 2 L grab sample taken at mid-channel at the X-site in an amber bottle, filtered and analyzed in a laboratory.":
        "Water-column chlorophyll a (µg/L) from a 2 L mid-channel grab sample at the X-site, collected in an amber bottle, filtered and analyzed in a lab.",
    "Specific conductance in microsiemens per centimeter. NRSA reports the laboratory value of a grab sample taken at mid-channel at the X-site (the center of the reach). A calibrated multi-parameter meter reads the same quantity in the stream at that point.":
        "Specific conductance (µS/cm). NRSA reports the lab value of a mid-channel grab sample at the X-site (the reach center); a calibrated multi-parameter meter reads the same quantity in the stream there.",
    "Total nitrogen in milligrams of nitrogen per liter, laboratory analysis of the unfiltered mid-channel grab sample from the X-site, kept on ice.":
        "Total nitrogen (mg N/L), lab analysis of the unfiltered mid-channel grab sample from the X-site, kept on ice.",
    "pH of the mid-channel grab sample from the X-site, as NRSA reports it. A calibrated multi-parameter meter reads pH in the stream at the same point, at 0.5 m depth or mid-depth in shallow water.":
        "pH of the X-site mid-channel grab sample, as NRSA reports it, or a calibrated multi-parameter meter reading in the stream there at 0.5 m depth (mid-depth if shallower).",
    "Total phosphorus in micrograms per liter, laboratory analysis of the mid-channel grab sample from the X-site, kept on ice.":
        "Total phosphorus (µg/L), lab analysis of the mid-channel grab sample from the X-site, kept on ice.",
    "Turbidity in nephelometric turbidity units, laboratory analysis of the mid-channel grab sample from the X-site. Sample before anyone walks the channel upstream.":
        "Turbidity (NTU), lab analysis of the mid-channel grab sample from the X-site. Sample before anyone walks the channel upstream.",
    "Degree of regulation, the normal storage of upstream dams as a percent of mean annual runoff. DEEP reads both from EPA StreamCat for the reach. Nothing is measured in the field.":
        "Normal storage of upstream dams as a percent of mean annual runoff, both read from EPA StreamCat for the reach. No field measurement.",
    "Computed, not read in the field. From the upstream electrofishing pass over every habitat between the transects, with every fish identified and counted, score EPA's eight regional fish metrics, several adjusted for watershed area, and rescale to 0 to 100, as the 2018-19 technical support document describes.":
        "Computed: from the upstream electrofishing pass (every habitat between the transects, every fish identified and counted), score EPA's 8 regional fish metrics, several adjusted for watershed area, and rescale to 0 to 100 (NRSA 2018-19 technical support document).",
    "From the same upstream electrofishing pass over every habitat between the transects, with every fish identified and counted. The value is the percent of native individuals that are simple lithophils, spawning on clean coarse substrate without building a nest.":
        "From the upstream electrofishing pass over every habitat between the transects (every fish identified and counted). Value: percent of native individuals that are simple lithophils, spawning on clean coarse substrate without a nest.",
    "From the same upstream electrofishing pass over every habitat between the transects, with every fish identified and counted. The value is the number of native taxa that are not classed tolerant.":
        "From the upstream electrofishing pass over every habitat between the transects (every fish identified and counted). Value: number of native taxa not classed tolerant.",
    "From the same upstream electrofishing pass over every habitat between the transects, with every fish identified and counted. The value is the percent of native taxa that are not classed tolerant.":
        "From the upstream electrofishing pass over every habitat between the transects (every fish identified and counted). Value: percent of native taxa not classed tolerant.",
    "From the same upstream electrofishing pass over every habitat between the transects, with every fish identified and counted. The value is the percent of native individuals that belong to tolerant taxa.":
        "From the upstream electrofishing pass over every habitat between the transects (every fish identified and counted). Value: percent of native individuals in tolerant taxa.",
    "Electrofish the sampling reach in an upstream direction, working every habitat between the transects, and identify and count every fish. The value is the number of native taxa.":
        "Electrofish the reach upstream through every habitat between the transects, identifying and counting every fish. Value: number of native taxa.",
    "Natural cover of the 100 m riparian corridor of the watershed: forest, shrub, grassland and wetland, percent (NLCD 2019 through StreamCat's riparian buffers), the input EASI's organic-matter supply method reads; DEEP fills it from the desktop analysis and the user may correct it.":
        "Percent natural cover (forest, shrub, grassland, wetland) in the watershed's 100 m riparian corridor (NLCD 2019, StreamCat riparian buffers), the input EASI's organic-matter supply method reads. DEEP fills it in; you can correct it.",
    "Number of dams in the USACE National Inventory of Dams within one mile of the site. DEEP counts them. Note in the field any barrier the inventory does not show.":
        "Dams in the USACE National Inventory of Dams within 1 mile of the site, counted by DEEP. Note in the field any barrier the inventory does not show.",
    "Percent of the watershed in cultivated crops plus hay and pasture. DEEP computes it for the delineated watershed. Nothing is measured in the field.":
        "Percent of the delineated watershed in cultivated crops plus hay and pasture, computed by DEEP. No field measurement.",
    "Percent of the watershed in impervious surface. DEEP computes it for the delineated watershed. Nothing is measured in the field.":
        "Percent of the delineated watershed in impervious surface, computed by DEEP. No field measurement.",
    "Percent of the watershed in woody plus herbaceous wetland (NLCD 2019). DEEP reads it from EPA StreamCat for the reach. Nothing is measured in the field.":
        "Percent of the watershed in woody plus herbaceous wetland (NLCD 2019), read from EPA StreamCat for the reach. No field measurement.",
    "Watershed wetland cover (NLCD 2019 woody plus herbaceous wetland, percent of the watershed) from the StreamCat lookup engine or the STAF site engine; DEEP fills it from the desktop analysis and the user may correct it.":
        "Percent of the watershed in woody plus herbaceous wetland (NLCD 2019). DEEP fills it in from desktop data; you can correct it.",
    "At each transect, measure the bankfull width and the bankfull height above the water surface, and the thalweg depth. The value is the mean bankfull width divided by the mean bankfull depth (bankfull height plus thalweg depth).":
        "At each transect, measure bankfull width, bankfull height above the water surface and thalweg depth. Value: mean bankfull width divided by mean bankfull depth (bankfull height plus thalweg depth).",
    "Computed, not read in the field. It is the base 10 logarithm of the ratio of the geometric mean particle diameter to the largest diameter the bankfull flow can move, from the particle count, reach slope, bankfull depth, wood tally and residual pools, with the NRSA physical habitat calculations.":
        "Computed: the base 10 log of the geometric mean particle diameter divided by the largest diameter the bankfull flow can move, from the particle count, reach slope, bankfull depth, wood tally and residual pools (NRSA physical habitat calculations).",
    "From the same 105-particle size class count as sand and fines. The value is the base 10 logarithm of the geometric mean particle diameter in millimeters, computed from the size classes with the NRSA physical habitat calculations.":
        "From the 105-particle size class count (as for sand and fines). Value: base 10 log of the geometric mean particle diameter in mm, from the size classes (NRSA physical habitat calculations).",
    "Between each pair of transects, tally every piece of wood at least 10 cm in diameter and 1.5 m long in or above the bankfull channel, by length and diameter class. The value is the wood volume per 100 m of channel, computed from the tally classes.":
        "Between each pair of transects, tally every piece of wood at least 10 cm in diameter and 1.5 m long in or above the bankfull channel, by length and diameter class. Value: wood volume per 100 m of channel, from the tally.",
    "At each thalweg station record the channel unit (falls, cascade, rapid, riffle, glide, pool, dry). The value is the percent of stations in fast water (falls, cascade, rapid or riffle).":
        "At each thalweg station, record the channel unit (falls, cascade, rapid, riffle, glide, pool, dry). Value: percent of stations in falls, cascade, rapid or riffle.",
    "Record the size class of the particle at five evenly spaced points across each of the 11 transects and the 10 cross-sections midway between them (105 particles). The value is the percent of particles that are sand or finer.":
        "Record the particle size class at 5 evenly spaced points on each of the 11 transects and the 10 cross-sections midway between them (105 particles). Value: percent sand or finer.",
    "Measure the thalweg depth at 10 or 15 evenly spaced stations between each pair of transects (100 or 150 along the reach). The value is the mean residual pool depth in centimeters, computed from that depth profile and the reach slope with the NRSA physical habitat calculations.":
        "Measure thalweg depth at 10 or 15 evenly spaced stations between each pair of transects (100 or 150 per reach). Value: mean residual pool depth in cm, from that profile and the reach slope (NRSA physical habitat calculations).",
    "Take a compass bearing (backsight) and the distance between each pair of neighboring transects. The value is the channel length along those segments divided by the straight line distance between the ends of the reach.":
        "Take a compass backsight bearing and the distance between each pair of neighboring transects. Value: channel length along those segments divided by the straight-line distance between the reach ends.",
    "At the left and the right bank of each transect, lay a pole about one meter long against the bank and read its angle from horizontal with a clinometer, in degrees. The value is the mean of the 22 readings.":
        "On both banks of each transect, lay a pole about 1 m long against the bank and read its angle from horizontal with a clinometer, in degrees. Value: mean of the 22 readings.",
    "At each transect, measure the height of the bankfull elevation above the present water surface in meters, with a rod at the water's edge and a clinometer held level at bankfull. The value is the mean of the 11 heights.":
        "At each transect, measure the bankfull height above the present water surface in m, with a rod at the water's edge and a clinometer held level at bankfull. Value: mean of the 11 heights.",
    "At mid-channel on each transect, read a convex spherical densiometer facing upstream, downstream, left and right, counting the covered points of 17. The value is the mean of the 44 readings as a percent.":
        "At mid-channel on each transect, read a convex spherical densiometer facing upstream, downstream, left and right (covered points of 17). Value: mean of the 44 readings, as a percent.",
    "In a 10 m by 10 m plot on each bank at each transect, estimate the areal cover class of woody vegetation in the canopy, the understory and the ground layer. The value is the summed woody cover of the three layers, averaged over the 22 plots, as a fraction.":
        "In a 10 m by 10 m plot on each bank at each transect, estimate the areal cover class of woody vegetation in the canopy, understory and ground layer. Value: summed woody cover of the 3 layers, averaged over the 22 plots, as a fraction.",
    "At five evenly spaced points across each of the 11 transects, estimate how much of the particle under the point is buried in sand and finer sediment, in percent. Record the 55 estimates. The value is their mean.":
        "At 5 evenly spaced points on each of the 11 transects, estimate the percent of the particle buried in sand or finer sediment. Value: mean of the 55 estimates.",
    "In the 10 m of channel centered on each transect, estimate the areal cover class of each fish cover type on the form (wood, brush, overhanging vegetation, undercut banks, boulders and the rest). The value is the summed areal cover of the types that are not man-made, averaged over the transects.":
        "In the 10 m of channel centered on each transect, estimate the areal cover class of each fish cover type on the form (wood, brush, overhanging vegetation, undercut banks, boulders, others). Value: summed cover of the natural types, averaged over the transects.",
    "Road length per square kilometer of watershed. DEEP computes it for the delineated watershed. Nothing is measured in the field.":
        "Road length per square kilometer of the delineated watershed, computed by DEEP. No field measurement.",
    "Base-flow index (% of streamflow from baseflow); a higher baseflow share indicates a more stable, groundwater-supported flow regime. Moderate confidence: hydrogeology sets the baseline, so a naturally flashy till catchment reads low without being degraded (see the natural-context criterion below). Scored because flow alteration and withdrawal also move it. Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id. Base-flow index is the mean of the USGS base-flow index grid (Wolock 2003, 1 km) over the HR reach watershed.":
        "Base flow index (% of streamflow from base flow); higher means a steadier, groundwater-fed regime. Hydrogeology sets the baseline, so a naturally flashy till catchment reads low without being degraded (moderate confidence). Scored because flow alteration and withdrawal also move it. Computed by DEEP as the mean of the USGS base flow index grid (Wolock 2003, 1 km) over the watershed.",
    "Base-flow index (% of streamflow from baseflow); a higher baseflow share indicates a more stable, groundwater-supported flow regime. Moderate confidence: hydrogeology sets the baseline, so a naturally flashy till catchment reads low without being degraded (see the natural-context criterion below). Scored because flow alteration and withdrawal also move it.":
        "Base flow index (% of streamflow from base flow); higher means a steadier, groundwater-fed regime. Hydrogeology sets the baseline, so a naturally flashy till catchment reads low without being degraded (moderate confidence). Scored because flow alteration and withdrawal also move it.",
    "Total nitrogen; higher indicates nutrient enrichment (worse). The total fraction, reported in every NRSA cycle, and the fraction published nitrogen criteria are written against.":
        "Total nitrogen; higher indicates nutrient enrichment (worse). The total fraction is reported in every NRSA cycle and is the one published nitrogen criteria use.",
    "Dam density (dams per sq km); impoundment alters the natural flow regime and fragments the network. Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id.":
        "Dam density (dams per sq km); impoundment alters the natural flow regime and fragments the network. Computed by DEEP for the watershed from NID dams.",
    "Native non-tolerant fish taxa richness (TOLERANCE_NRSA); higher is better. Total richness need not fall under disturbance, because tolerant species replace intolerant ones; this counts only the taxa that do not tolerate it.":
        "Native non-tolerant fish taxa richness (TOLERANCE_NRSA); higher is better. It counts only taxa that do not tolerate disturbance, since tolerant species can replace intolerant ones without lowering total richness.",
    "Percent of native fish taxa not classed tolerant (TOLERANCE_NRSA); higher is better. A proportion, so it does not carry the size of a region's species pool the way a richness count does.":
        "Percent of native fish taxa not classed tolerant (TOLERANCE_NRSA); higher is better. As a proportion, it does not scale with a region's species pool the way richness does.",
    "Watershed cultivated crops (%); row-crop conversion degrades infiltration, soil structure, and runoff timing. Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id.":
        "Watershed cultivated crops (%); row-crop conversion degrades infiltration, soil structure and runoff timing. Computed by DEEP for the watershed from NLCD 2021.",
    "Watershed impervious surface (%); imperviousness drives flashier runoff, reduced infiltration, and degraded catchment hydrology. Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id.":
        "Watershed impervious surface (%); imperviousness drives flashier runoff, reduced infiltration and degraded catchment hydrology. Computed by DEEP for the watershed from NLCD 2021.",
    "Watershed wetland (%), woody plus herbaceous, both classes required; wetlands store surface water and attenuate flow peaks. EASI scores Surface water storage on the same sum (method watershed-wetland-extent). Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id. Wetland cover is the sum of the engine's woody and herbaceous wetland percentages over the HR reach watershed; both classes are required, and a missing one leaves the total unknown rather than smaller.":
        "Watershed wetland (%), woody plus herbaceous. Both classes are required: a missing one leaves the total unknown, not smaller. Wetlands store surface water and attenuate flow peaks; EASI scores Surface water storage on the same sum. Computed by DEEP for the watershed from NLCD 2021.",
    "Watershed wetland (%), woody plus herbaceous, both classes required; wetlands store surface water and attenuate flow peaks. EASI scores Surface water storage on the same sum (method watershed-wetland-extent).":
        "Watershed wetland (%), woody plus herbaceous, both classes required. Wetlands store surface water and attenuate flow peaks; EASI scores Surface water storage on the same sum.",
    "Log relative bed stability; departure from the reference core in EITHER direction departs from reference (negative excess fines, positive an armored, sediment-starved bed, the classic below-impoundment failure). The pilot's rising direction scored armored beds 1.0 and left Sediment continuity blind to its textbook failure mode. Two-sided form is an owner decision at the adversarial review gate, 2026-08-21.":
        "Log relative bed stability; departure from the reference core in either direction departs from reference: negative means excess fines, positive an armored, sediment-starved bed (the classic below-impoundment failure). Two-sided, so armored beds no longer score 1.0 as on the pilot's rising curve (owner decision, 2026-08-21).",
    "Mean bank angle; very steep banks indicate incision and very flat banks an over-widened, aggrading channel, so departure from the reference core in either direction departs from reference. Direction resolved at the Northeastern Highlands review gate (owner decision, 2026-08-21), consistent with the width-to-depth and bankfull-height treatment. low_tail flat added at the adversarial review gate (owner decision, 2026-08-21): a regraded or naturally gentle bank holds at the Functioning edge instead of being penalized, because the flat tail is not symmetric evidence of degradation and the framework's stated use is restoration evaluation.":
        "Mean bank angle; very steep banks indicate incision and very flat banks an over-widened, aggrading channel, so departure from the reference core in either direction departs from reference, as for width-to-depth and bankfull height (owner decision, 2026-08-21). A regraded or naturally gentle bank holds at the Functioning edge rather than being penalized, since restoration evaluation is the framework's stated use (owner decision, 2026-08-21).",
    "Mean bank angle; very steep banks indicate incision and very flat banks an over-widened, aggrading channel, so departure from the reference core in either direction departs from reference. Direction resolved at the Northeastern Highlands review gate (owner decision, 2026-08-21), consistent with the width-to-depth and bankfull-height treatment.":
        "Mean bank angle; very steep banks indicate incision and very flat banks an over-widened, aggrading channel, so departure from the reference core in either direction departs from reference, as for width-to-depth and bankfull height (owner decision, 2026-08-21).",
    "Road/stream crossing density; crossings fragment aquatic habitat and impede organism passage. UNITS CAUTION (2026-08-21): values as served by the EPA StreamCat API sit about two orders of magnitude below the classic StreamCat documentation of crossings per sq km (frame national median 0.0098 vs a documented distribution near 0.5 to 1.5). The frame and the live API agree with each other, so scoring is internally consistent, but a manually computed crossings-per-sq-km value will land far off-curve. Enter API-served values only, pending units reconciliation with EPA. Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id. Road-stream crossings are counted where TIGERweb roads meet the NHDPlus HR network, per km2 of watershed, so this curve's scale is the engine's and not StreamCat's served rdcrs.":
        "Road-stream crossing density; crossings fragment habitat and impede organism passage. Units caution (2026-08-21): EPA StreamCat API values sit about two orders of magnitude below the documented crossings per sq km (frame national median 0.0098 vs about 0.5 to 1.5), so a hand-computed value lands far off the curve; enter API values only. DEEP counts crossings where TIGERweb roads meet the NHDPlus HR network, per km2 of watershed, so this curve's scale is DEEP's, not StreamCat's.",
    "Road/stream crossing density; crossings fragment aquatic habitat and impede organism passage. UNITS CAUTION (2026-08-21): values as served by the EPA StreamCat API sit about two orders of magnitude below the classic StreamCat documentation of crossings per sq km (frame national median 0.0098 vs a documented distribution near 0.5 to 1.5). The frame and the live API agree with each other, so scoring is internally consistent, but a manually computed crossings-per-sq-km value will land far off-curve. Enter API-served values only, pending units reconciliation with EPA.":
        "Road-stream crossing density; crossings fragment habitat and impede organism passage. Units caution (2026-08-21): EPA StreamCat API values sit about two orders of magnitude below the documented crossings per sq km (frame national median 0.0098 vs about 0.5 to 1.5). Scoring is internally consistent, but a hand-computed value lands far off the curve, so enter API values only until EPA reconciles the units.",
    "Watershed road density; roads concentrate and route runoff to the channel, so higher density means more concentrated inflow pressure. Directional proxy shared with the EASI screening metric; it does not count outfalls. Values recomputed by the STAF site engine v0.4.1 over the HR reach watershed (NLCD 2021, TIGERweb roads, NID dams, the USGS base-flow index grid). The StreamCat column name is kept for the metric id.":
        "Watershed road density; roads concentrate runoff and route it to the channel, so higher density means more inflow pressure. A directional proxy shared with EASI's screening metric; it does not count outfalls. Computed by DEEP for the watershed from TIGERweb roads.",
    "Watershed road density; roads concentrate and route runoff to the channel, so higher density means more concentrated inflow pressure. Directional proxy shared with the EASI screening metric; it does not count outfalls.":
        "Watershed road density; roads concentrate runoff and route it to the channel, so higher density means more inflow pressure. A directional proxy shared with EASI's screening metric; it does not count outfalls.",
}


def _norm(text) -> str:
    return " ".join(str(text or "").split())


def concise(text) -> str:
    """The concise wording of a published method text, or the text itself when it
    has none."""
    t = _norm(text)
    return CONCISE.get(t, t)
