"""The NRSA harmonization audit (config/nrsa_harmonization_audit.csv and .md).

Both files are generated by ``scripts/nrsa/build_harmonization_audit.py`` from
the multi-cycle archive. The drift gate is the load-bearing test: the committed
files must be what a fresh build writes, so a rebuilt archive or an edited
compatibility file shows up here rather than in a stale audit. The build runs
once per module (a few seconds) and every test reads the cached result.
"""
from __future__ import annotations

import csv
import importlib.util
from pathlib import Path

import pytest

from streamcurves import nrsa_dataset as nd
from streamcurves import reference_screen as rs

APP = Path(__file__).resolve().parents[1]
SCRIPT = APP / "scripts" / "nrsa" / "build_harmonization_audit.py"

pytestmark = pytest.mark.skipif(
    not (nd.multi_cycle_available() and rs.station_screen_available()),
    reason="multi-cycle archive not built (scripts/nrsa/build_values_table.py)")

# the frame counts tests/test_station_screen.py pins for the owner's census
FRAME_STATIONS = 3267
STRICT_STATIONS = 770
PINNED_METRIC = "chem_NTL"


@pytest.fixture(scope="module")
def audit():
    spec = importlib.util.spec_from_file_location("build_harmonization_audit", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    rows, summary = mod.build()
    return mod, rows, summary


def _committed(mod) -> list[dict]:
    with open(mod.CSV_PATH, encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


# --------------------------------------------------------------------------- #
# the files are the build's
# --------------------------------------------------------------------------- #
def test_the_committed_csv_matches_a_fresh_build(audit):
    mod, rows, _ = audit
    assert mod.CSV_PATH.read_bytes() == mod.render_csv(rows).encode("utf-8")


def test_the_committed_summary_matches_a_fresh_build(audit):
    mod, _, summary = audit
    assert mod.MD_PATH.read_bytes() == mod.render_md(summary).encode("utf-8")


def test_check_mode_reports_no_drift(audit):
    mod, rows, summary = audit
    assert mod.drift(rows, summary) == []


def test_an_edited_row_is_reported(audit):
    mod, rows, summary = audit
    edited = [dict(r) for r in rows]
    edited[0]["n_values"] = str(int(edited[0]["n_values"] or 0) + 1)
    assert mod.drift(edited, summary) == ["nrsa_harmonization_audit.csv differs from a fresh build"]


# --------------------------------------------------------------------------- #
# the rows
# --------------------------------------------------------------------------- #
def test_every_mapped_metric_has_its_cycle_rows_and_a_pooled_row(audit):
    mod, rows, _ = audit
    metrics = mod.mapped_nrsa_metrics()
    compat = nd.cycle_compatibility()
    by_metric: dict[str, set] = {}
    for r in rows:
        by_metric.setdefault(r["metric_key"], set()).add(r["cycle"])
    assert set(by_metric) == set(metrics)
    for metric in metrics:
        eligible = compat.get(metric, set(mod.CYCLES))
        assert eligible <= by_metric[metric], metric
        assert mod.POOLED in by_metric[metric], metric
        assert by_metric[metric] == set(mod.CYCLES) | {mod.POOLED}, metric
    assert len(rows) == len(metrics) * (len(mod.CYCLES) + 1)


def test_the_columns_are_the_contract(audit):
    mod, _, _ = audit
    committed = _committed(mod)
    assert list(committed[0].keys()) == mod.COLUMNS
    must = ["metric_key", "cycle", "eligible", "epa_short_name", "epa_definition", "units",
            "origin", "n_values", "n_stations_frame", "n_stations_strict",
            "missingness_in_frame", "protocol_wadeable_n", "protocol_boatable_n", "zero_share",
            "out_of_domain_n", "detection_limit_handling", "min", "q25", "median", "q75", "max",
            "n_selected", "share_not_newest", "multi_cycle_stations", "median_abs_rel_change",
            "repeat_pairs_n", "repeat_median_abs_diff", "repeat_within_10pct_share", "problems"]
    assert [c for c in must if c not in mod.COLUMNS] == []


def test_the_files_are_lf_and_sorted(audit):
    mod, _, _ = audit
    for path in (mod.CSV_PATH, mod.MD_PATH):
        raw = path.read_bytes()
        assert b"\r" not in raw, path.name
        assert raw.endswith(b"\n"), path.name
    keys = [(r["metric_key"], r["cycle"]) for r in _committed(mod)]
    assert keys == sorted(keys)
    assert len(set(keys)) == len(keys)
    # pooled sorts after the three cycles, so each metric's block ends with it
    assert [k for k in keys if k[1] == mod.POOLED] == [
        k for k in keys if k[1] not in mod.CYCLES]


def test_nothing_volatile_is_written(audit):
    mod, _, _ = audit
    for path in (mod.CSV_PATH, mod.MD_PATH):
        text = path.read_text(encoding="utf-8")
        assert "D:\\" not in text and "/Users/" not in text and "C:\\" not in text, path.name
        assert "\u2014" not in text, path.name


# --------------------------------------------------------------------------- #
# the frame is the run's own
# --------------------------------------------------------------------------- #
def test_the_pooled_frame_totals_are_the_station_screen_counts(audit):
    """The denominators the audit reports are the DATA-10 run frame pinned in
    tests/test_station_screen.py (3,267 in frame, 770 strict), never the screen
    table's order-only wadeable column (3,190)."""
    mod, rows, summary = audit
    pooled = {r["metric_key"]: r for r in rows if r["cycle"] == mod.POOLED}
    row = pooled[PINNED_METRIC]
    assert int(row["frame_stations_sampled"]) == FRAME_STATIONS
    assert int(row["strict_stations_sampled"]) == STRICT_STATIONS
    assert summary["frame"] == FRAME_STATIONS and summary["strict"] == STRICT_STATIONS
    assert summary["order_only_wadeable"] < FRAME_STATIONS
    for metric, r in pooled.items():
        assert int(r["frame_stations_sampled"]) == FRAME_STATIONS, metric
        assert int(r["strict_stations_sampled"]) == STRICT_STATIONS, metric
        assert int(r["n_stations_frame"]) <= FRAME_STATIONS, metric
        assert int(r["n_stations_strict"]) <= int(r["n_stations_frame"]), metric


def test_cycle_rows_never_exceed_their_denominators(audit):
    mod, rows, _ = audit
    for r in rows:
        if r["cycle"] == mod.POOLED:
            continue
        assert int(r["n_stations_frame"]) <= int(r["frame_stations_sampled"]), r["metric_key"]
        assert int(r["n_stations_strict"]) <= int(r["strict_stations_sampled"]), r["metric_key"]
        assert (int(r["protocol_wadeable_n"]) + int(r["protocol_boatable_n"])
                <= int(r["n_stations_frame"])), r["metric_key"]


def test_the_pooled_selection_is_the_data_11_ledger(audit):
    """n_selected on the pooled row is what nrsa_dataset.latest_values hands a
    build for the same metric over every archive station."""
    mod, rows, _ = audit
    row = next(r for r in rows if r["metric_key"] == PINNED_METRIC and r["cycle"] == mod.POOLED)
    stations = nd.load_dataset(nd.MULTI_CYCLE_DATASET_ID).stations["station_key"].astype(str)
    _, ledger = nd.latest_values(list(stations), dataset=nd.MULTI_CYCLE_DATASET_ID,
                                 metrics=[PINNED_METRIC])
    assert int(row["n_selected"]) == int(len(ledger))
    assert row["pooled_cycles"] == ",".join(mod.CYCLES)


def test_a_backfilled_cycle_contributes_no_repeat_pairs(audit):
    """The 2018-19 benthic and fish values are copies of one per-site value on
    every visit, so their second visits cannot measure precision."""
    mod, rows, _ = audit
    for r in rows:
        if r["origin"] == "legacy_r_app" and r["cycle"] != mod.POOLED:
            assert r["repeat_pairs_n"] == "0", r["metric_key"]
            assert r["origin_rationale"], r["metric_key"]
