"""Generate config/fixed_criteria.yaml from the vendored EASI scoring catalog.

The fixed criteria DEEP scores its pressure metrics on are EASI's, so they are
read from EASI's own catalog and never typed by hand (rule CURVE-11). Run this
after every re-vendor of EASI; ``tests/test_fixed_criteria.py`` fails until the
committed file matches the catalog again.

    py -3.12 scripts/build_fixed_criteria.py            # write the file
    py -3.12 scripts/build_fixed_criteria.py --check    # exit 1 when it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

APP_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(APP_ROOT))

from streamcurves import fixed_criteria as fc  # noqa: E402

HEADER = """\
# fixed_criteria.yaml
# GENERATED by scripts/build_fixed_criteria.py from the vendored EASI scoring
# catalog (streamcurves/_vendor/easi/data/screening-methods.json). Do not edit
# by hand: tests/test_fixed_criteria.py compares this file with the catalog.
#
# Rule CURVE-11 (methodology 0.12): landscape pressure metrics are scored on
# EASI's cited criteria, identical in every region, drawn as a continuous curve
# (see streamcurves/fixed_criteria.py for the construction). Expectation metrics
# (field metrics, wetland cover, base flow index) keep regional reference curves.
"""


def render() -> str:
    doc = fc.generate()
    body = yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100,
                          default_flow_style=None)
    return HEADER + "\n" + body


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare the committed file with the catalog; write nothing")
    a = ap.parse_args()
    if a.check:
        fc.clear_cache()
        problems = fc.criteria_drift()
        for p in problems:
            print(f"  - {p}")
        print("fixed criteria: " + ("ok" if not problems else f"{len(problems)} difference(s)"))
        return 1 if problems else 0
    text = render()
    fc.FIXED_CRITERIA_PATH.write_text(text, encoding="utf-8", newline="\n")
    fc.clear_cache()
    doc = fc.load_fixed_criteria()
    for key, e in (doc.get("metrics") or {}).items():
        pts = ", ".join(f"({x:g}, {y:g})" for x, y in e["points"])
        print(f"  {key:14s} {pts}")
    print(f"wrote {fc.FIXED_CRITERIA_PATH.relative_to(APP_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
