"""Generate config/staf_metric_library.json from the state SQT registry.

``config/staf_metric_library.json`` is the bundled master Function -> Metric mapping
the metric workbench prefills from (``streamcurves/staf_library.py``; the other
readers, ``views/discipline_map.py``, ``streamcurves/candidates.py`` and
``scripts/nrsa/build_metric_dictionary.py``, read it through the same fields).
Until 2026-09-25 its header named a producer that did not exist. This is that
producer; ``tests/test_staf_metric_library.py`` fails until the committed file
matches a fresh build again.

Inputs, and what each supplies:

* ``data/sqt/registry.json`` (generated by ``scripts/build_sqt_registry.py``): the
  102 detailed metrics of the eight state SQTs, one record per state, metric and
  stratum. Each metric's id (``stafMetricId``), label (``originalMetricName``),
  primary function (``function.id``) and citing states (``citation``) come from
  here.
* ``config/staf_functions.json``: the 20 functions in canonical order, which orders
  the file, and the ids every function reference must resolve to.
* ``config/metric_map.yaml``: checks the app-metric crosswalk below; every code and
  source it names must still exist there.
* Recorded here, because no generated file carries them: the additional functions
  eleven metrics also serve (``ADDITIONAL_FUNCTIONS``), the crosswalk from a
  library metric to the app metric that measures it (``APP_METRIC_KEYS``), and one
  label spelling (``LABELS``). They are the 2026-07 builder's inputs, kept as data
  so the file reproduces byte for byte; change them here, never in the output.

    py -3.12 scripts/build_staf_metric_library.py            # write the file
    py -3.12 scripts/build_staf_metric_library.py --check    # exit 1 when it is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

APP_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(APP_ROOT))

REGISTRY_PATH = APP_ROOT / "data" / "sqt" / "registry.json"
FUNCTIONS_PATH = APP_ROOT / "config" / "staf_functions.json"
METRIC_MAP_PATH = APP_ROOT / "config" / "metric_map.yaml"
OUT_PATH = APP_ROOT / "config" / "staf_metric_library.json"

#: The functions a metric serves beside the one its id names (the SQT tools
#: score each metric under one function; STAF's crosswalk also reads these
#: eleven for a second one). Function ids of config/staf_functions.json.
ADDITIONAL_FUNCTIONS: dict[str, list[str]] = {
    "catchment-hydrology-impervious-cover": ["streamflow-regime"],
    "catchment-hydrology-land-use-coefficient": ["surface-water-storage"],
    "floodplain-connectivity-entrenchment-ratio-er": ["surface-water-storage"],
    "channel-evolution-width-depth-ratio": ["low-flow-baseflow-dynamics"],
    "channel-and-floodplain-dynamics-bank-height-ratio-bhr": ["high-flow-dynamics"],
    "channel-and-floodplain-dynamics-percent-streambank-erosion": ["channel-evolution"],
    "carbon-processing-riparian-extent": ["nutrient-cycling"],
    "habitat-provision-lwd": ["bed-composition-bedform-dynamics"],
    "habitat-provision-lwd-index": ["bed-composition-bedform-dynamics"],
    "habitat-provision-percent-riffle": ["sediment-continuity", "watershed-connectivity"],
    "habitat-provision-pool-spacing-ratio": ["hyporheic-connectivity"],
}

#: library id -> (app metric key, catalog source): the app metric that measures
#: what the SQT metric measures, where one does (a data-backed entry). Every
#: code must exist in config/metric_map.yaml under the same source.
APP_METRIC_KEYS: dict[str, tuple[str, str]] = {
    "catchment-hydrology-effective-impervious-cover": ("pctimp2019", "streamcat"),
    "catchment-hydrology-impervious-cover": ("pctimp2019", "streamcat"),
    "catchment-hydrology-percent-impervious-cover": ("pctimp2019", "streamcat"),
    "channel-evolution-width-depth-ratio": ("phab_BFWD_RAT", "nrsa"),
    "channel-evolution-width-depth-ratio-state": ("phab_BFWD_RAT", "nrsa"),
    "channel-and-floodplain-dynamics-sinuosity": ("phab_SINU", "nrsa"),
    "nutrient-cycling-total-phosphorus": ("chem_PTL", "nrsa"),
    "water-and-soil-quality-daily-average-turbidity": ("chem_TURB", "nrsa"),
    "water-and-soil-quality-tss-and-turbidity": ("chem_TURB", "nrsa"),
    "water-and-soil-quality-specific-conductivity": ("chem_COND", "nrsa"),
}

#: The metric library's canonical spelling where it differs from the SQT row's:
#: the docs metric library merges a rapid-tier row "Dissolved oxygen" with the
#: Michigan detailed row "Dissolved Oxygen" under one id and keeps the first.
LABELS: dict[str, str] = {
    "water-and-soil-quality-dissolved-oxygen": "Dissolved oxygen",
}

COMMENT = (
    "Bundled master Function->Metric default mapping for the stream-curves workbench. "
    "GENERATED by scripts/build_staf_metric_library.py from data/sqt/registry.json (the "
    "102 detailed metrics of the eight state SQTs: id, label, primary function, citing "
    "states) plus the additional-function pairs and the app-metric crosswalk the script "
    "records, checked against config/metric_map.yaml. Do not edit by hand: "
    "tests/test_staf_metric_library.py compares this file with a fresh build. Discipline "
    "is derived at load from primary_function_id via config/staf_functions.json."
)
SOURCE = "data/sqt/registry.json (8-state union) + scripts/build_staf_metric_library.py crosswalks"


def _json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def function_ids() -> list[str]:
    """The 20 function ids in the crosswalk's canonical order."""
    return [str(f["id"]) for f in _json(FUNCTIONS_PATH)["functions"]]


def metric_map_sources() -> dict[str, str]:
    """``{code: source}`` for every metric config/metric_map.yaml lists."""
    doc = yaml.safe_load(METRIC_MAP_PATH.read_text(encoding="utf-8")) or {}
    out: dict[str, str] = {}
    for fn in doc.get("functions") or []:
        for entry in fn.get("metrics") or []:
            code, source = entry.get("code"), entry.get("source")
            if code and source:
                out.setdefault(str(code), str(source))
    return out


def build(registry_path: Path = REGISTRY_PATH) -> dict:
    """The library document, from the registry and the recorded crosswalks."""
    order = function_ids()
    rank = {fid: i for i, fid in enumerate(order)}
    records = _json(registry_path).get("records") or []
    by_id: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        if r.get("stafMetricId"):
            by_id[str(r["stafMetricId"])].append(r)
    if not by_id:
        raise ValueError(f"{registry_path} carries no stafMetricId records")

    sources = metric_map_sources()
    for lib_id, (code, source) in APP_METRIC_KEYS.items():
        if lib_id not in by_id:
            raise ValueError(f"APP_METRIC_KEYS names {lib_id!r}, which the registry lacks")
        if sources.get(code) != source:
            raise ValueError(
                f"APP_METRIC_KEYS maps {lib_id!r} to {code!r} ({source}), which "
                f"config/metric_map.yaml does not list under that source")
    for lib_id, extra in ADDITIONAL_FUNCTIONS.items():
        if lib_id not in by_id:
            raise ValueError(f"ADDITIONAL_FUNCTIONS names {lib_id!r}, which the registry lacks")
        for fid in extra:
            if fid not in rank:
                raise ValueError(f"ADDITIONAL_FUNCTIONS names function {fid!r}, unknown to "
                                 "config/staf_functions.json")

    metrics: list[dict] = []
    for lib_id, recs in by_id.items():
        names = sorted({str(r.get("originalMetricName") or "") for r in recs})
        primaries = sorted({str((r.get("function") or {}).get("id") or "") for r in recs})
        if len(names) != 1 or len(primaries) != 1:
            raise ValueError(f"{lib_id}: the registry names {names} under {primaries}; "
                             "one label and one primary function are expected")
        primary = primaries[0]
        if primary not in rank:
            raise ValueError(f"{lib_id}: primary function {primary!r} is unknown to "
                             "config/staf_functions.json")
        additional = list(ADDITIONAL_FUNCTIONS.get(lib_id) or [])
        if primary in additional:
            raise ValueError(f"{lib_id}: {primary!r} is both primary and additional")
        key, source = APP_METRIC_KEYS.get(lib_id, (None, None))
        metrics.append({
            "library_id": lib_id,
            "label": LABELS.get(lib_id, names[0]),
            "primary_function_id": primary,
            "additional_function_ids": additional,
            "app_metric_key": key,
            "catalog_source": source,
            "source_citations": sorted({str(r.get("citation") or "") for r in recs}),
            "prefill": True,
        })
    # the crosswalk's function order, then the label, case-insensitively
    metrics.sort(key=lambda m: (rank[m["primary_function_id"]], m["label"].lower()))
    return {
        "schemaVersion": 1,
        "_comment": COMMENT,
        "source": SOURCE,
        "metricCount": len(metrics),
        "functionPairCount": sum(1 + len(m["additional_function_ids"]) for m in metrics),
        "multiFunctionCount": sum(1 for m in metrics if m["additional_function_ids"]),
        "metrics": metrics,
    }


def render(doc: dict) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def drift(out_path: Path = OUT_PATH, registry_path: Path = REGISTRY_PATH) -> list[str]:
    """Human-readable differences between the committed file and a fresh build."""
    fresh = render(build(registry_path))
    if not out_path.exists():
        return [f"{out_path.name} is missing"]
    committed = out_path.read_text(encoding="utf-8")
    if committed == fresh:
        return []
    problems: list[str] = []
    try:
        old, new = json.loads(committed), json.loads(fresh)
    except ValueError:
        return [f"{out_path.name} is not the JSON a fresh build writes"]
    for key in ("_comment", "source", "metricCount", "functionPairCount", "multiFunctionCount"):
        if old.get(key) != new.get(key):
            problems.append(f"{key} differs from a fresh build")
    old_by = {m.get("library_id"): m for m in old.get("metrics") or []}
    new_by = {m["library_id"]: m for m in new["metrics"]}
    for lib_id in sorted(set(old_by) | set(new_by)):
        if lib_id not in old_by:
            problems.append(f"{lib_id} is missing from the committed file")
        elif lib_id not in new_by:
            problems.append(f"{lib_id} is not in a fresh build")
        elif old_by[lib_id] != new_by[lib_id]:
            problems.append(f"{lib_id} differs from a fresh build")
    if [m.get("library_id") for m in old.get("metrics") or []] != list(new_by):
        problems.append("the metric order differs from a fresh build")
    return problems or [f"{out_path.name} differs from a fresh build (whitespace or key order)"]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare the committed file with a fresh build; write nothing")
    a = ap.parse_args(argv)
    if a.check:
        problems = drift()
        for p in problems:
            print(f"  - {p}")
        print("staf metric library: " + ("ok" if not problems else f"{len(problems)} difference(s)"))
        return 1 if problems else 0
    doc = build()
    OUT_PATH.write_text(render(doc), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH.relative_to(APP_ROOT)}: {doc['metricCount']} metrics, "
          f"{doc['functionPairCount']} function pairs, {doc['multiFunctionCount']} multi-function")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
