"""Write the candidate entries of the model registry from a pre-registered run.

Methodology 0.14, rule REF-13 and Pre-registration IV section 5.4. A modeled
specification that passes acceptance in a pre-registered recovery test enters
``config/model_registry.yaml`` as a CANDIDATE, with the application limits its
passing cells support. A candidate is never run: the owner approves an entry by
editing its status to ``approved`` with an ``approval`` record, which moves it out
of the generated block. Approved entries are never touched here.

The limits of a candidate come from the cells where the specification passed
(exceedance at least 0.10) in every regime it was accepted in:

  min_coverage_share    the smallest natural-coverage share among those cells
  max_disturbance_gap   per pressure, the largest gap between the cell's
                        least-disturbed training station and the national
                        reference point among those cells

    py -3.12 scripts/build_model_registry.py --run <folder> --prereg <file>
    py -3.12 scripts/build_model_registry.py --run <folder> --prereg <file> --check
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from streamcurves import acceptance                  # noqa: E402
from streamcurves import basis_recovery as br        # noqa: E402
from streamcurves import model_registry as mreg      # noqa: E402

BASIS = "1B_mixed_local"
PASSING_EXCEEDANCE = 0.10
BEGIN = "  # --- candidates: GENERATED by scripts/build_model_registry.py, do not hand-edit ---"
END = "  # --- end of generated candidates ---"


def candidates(run: Path, prereg: Path | None, approved: set[str]) -> list[dict]:
    records = pd.read_csv(run / "model.csv", dtype={"l3": str})
    records = records[records["basis"].astype(str) == BASIS]
    scored = br.score_verdicts(records, rule="prereg-2")
    sha = hashlib.sha256(prereg.read_bytes()).hexdigest() if prereg and prereg.exists() else None
    out = []
    for metric, rows in scored.groupby("metric", sort=True):
        if str(metric) in approved:
            continue
        accepted = [r for r in rows.to_dict("records")
                    if acceptance.acceptance_record(r).get("accepted")]
        if not accepted:
            continue
        regimes = sorted({str(r["regime"]) for r in accepted})
        cells = records[(records["metric"] == metric) & records["regime"].astype(str).isin(regimes)]
        passing = cells[pd.to_numeric(cells["exceedance"], errors="coerce") >= PASSING_EXCEEDANCE]
        if not len(passing):
            continue
        gaps = {}
        for col in [c for c in passing.columns if c.startswith("kept_gap_")]:
            v = pd.to_numeric(passing[col], errors="coerce").dropna()
            if len(v):
                gaps[col.replace("kept_gap_", "")] = round(float(max(0.0, v.max())), 4)
        cov = pd.to_numeric(passing["extrapolation_ok"], errors="coerce").dropna()
        best = max(accepted, key=lambda r: (r["verdict"] == br.VALIDATED, r.get("n_cells") or 0))
        out.append({
            "metric": str(metric), "procedure": "mixed_local", "status": mreg.CANDIDATE,
            "evidence": {
                "preregistration": prereg.name if prereg else None,
                "preregistration_sha256": sha, "run": str(run.as_posix()),
                "regime": ", ".join(regimes), "verdict": str(best["verdict"]),
                "n_cells": int(best.get("n_cells") or 0),
                "a1_share": None if best.get("a1_share") is None else float(best["a1_share"]),
                "net_opt": None if best.get("net_opt") is None else float(best["net_opt"]),
                "c3_share": None if best.get("c3_share") is None else float(best["c3_share"]),
                "passing_cells": sorted({str(x) for x in passing["l3"]}),
            },
            "limits": {"min_coverage_share": round(float(cov.min()), 4) if len(cov) else None,
                       "max_disturbance_gap": gaps},
        })
    return out


def render(existing: str, entries: list[dict]) -> str:
    body = yaml.safe_dump(entries, sort_keys=False, default_flow_style=False, width=100)
    block = "\n".join("  " + line if line else line for line in body.rstrip().splitlines()) \
        if entries else "  []"
    if entries:
        block = "\n".join(block.splitlines())
    gen = f"{BEGIN}\n{block if entries else '  # none'}\n{END}\n"
    if BEGIN in existing:
        head, rest = existing.split(BEGIN, 1)
        tail = rest.split(END, 1)[1].lstrip("\n")
        return head + gen + tail
    return existing.rstrip("\n") + "\n\n" + gen


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--run", required=True)
    ap.add_argument("--prereg", default=None)
    ap.add_argument("--registry", default=str(mreg.registry_path()))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    path = Path(a.registry)
    text = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    head = text.split(BEGIN, 1)[0]
    approved = {str(e.get("metric")) for e in (yaml.safe_load(head) or {}).get("entries") or []
                if e.get("status") == mreg.APPROVED}
    entries = candidates(Path(a.run), Path(a.prereg) if a.prereg else None, approved)
    new = render(text, entries)
    if a.check:
        same = new == text
        print(f"[registry] {'up to date' if same else 'STALE'}: {path}")
        return 0 if same else 1
    path.write_bytes(new.encode("utf-8"))
    print(f"[registry] {len(entries)} candidate(s) written to {path}")
    for e in entries:
        print(f"    {e['metric']:<22} {e['evidence']['verdict']:<10} regime {e['evidence']['regime']:<5}"
              f" cells {e['evidence']['passing_cells']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
