"""Run the national scale and stratifier analysis (rule STRAT-10).

One analysis over every least-disturbed station of the pooled NRSA archive
decides, per metric, the ecoregion level its reference values vary at and
whether a slope or drainage-area class split deserves its own curves. The
result is written to ``config/metric_scale_registry.yaml``, which every regional
build reads, and an evidence folder a reviewer can read beside it.

It reads the same inputs a build reads (``pressure_evidence.national_inputs``):
the committed station screen table and the archive, with the most recent
non-null value per metric. Offline. A few minutes at the default resampling
depth.

    py -3.12 scripts/run_national_scale_analysis.py --out <evidence folder>
    py -3.12 scripts/run_national_scale_analysis.py --out <folder> --dry-run   # no registry write
    py -3.12 scripts/run_national_scale_analysis.py --check                    # exit 1 when stale

The registry is a decision of record: regenerate it only when the station table,
the archive, or the rule changes, and review the evidence before committing it.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import pandas as pd
import yaml

APP_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(APP_ROOT))

from streamcurves import methodology, nrsa_dataset  # noqa: E402
from streamcurves import pressure_evidence as pe  # noqa: E402
from streamcurves import reference_pool as rp  # noqa: E402
from streamcurves import reference_screen as rscreen  # noqa: E402
from streamcurves import scale_analysis as sa  # noqa: E402

HEADER = """\
# metric_scale_registry.yaml
# GENERATED by scripts/run_national_scale_analysis.py (rule STRAT-10, methodology
# 0.12). A decision of record: regenerate it only when the station screen table,
# the NRSA archive, or the rule changes, and review the evidence folder first.
#
# Per metric: supported_level is the coarsest ecoregion level that keeps the
# Level III signal in the reference values (national when there is none), read
# on the bias-adjusted rank eta-squared (H-(k-1))/(n-k). A borrowed reference
# pool is at low transfer risk when it borrows from no coarser a level than this.
# split names a declared class split (NHDPlus slope or drainage area) that adds
# enough beyond that level, holds up under resampling by watershed, and does not
# lower agreement with EPA's own reference designation. A regional build applies
# a split only where its own pool holds two classes at the stratum floor.
"""

LEVEL_WORDS = {"l3": "Level III", "l2": "Level II", "l1": "Level I", "national": "national"}


def analyze(n_boot: int, seed: int, reference_frame: str, only=None, progress=print) -> dict:
    max_order, protocols = nrsa_dataset.governed_frame(reference_frame)
    inputs = pe.national_inputs(max_stream_order=max_order, protocols=protocols)
    frame, values, metric_config = inputs["frame"], inputs["values"], inputs["metric_config"]
    wide = values.set_index(values["site_id"].astype(str))
    keys = frame["station_key"].astype(str)
    results: dict[str, dict] = {}
    metrics = [m for m in metric_config if only is None or m in only]
    for i, mk in enumerate(metrics, start=1):
        series = pd.Series(keys.map(pd.to_numeric(wide[mk], errors="coerce")).to_numpy(),
                           index=frame.index) if mk in wide.columns \
            else pd.Series(float("nan"), index=frame.index)
        rec = sa.analyze_metric(mk, metric_config[mk], frame, series,
                                n_boot=n_boot, seed=seed)
        rec["display_name"] = metric_config[mk].get("display_name") or mk
        rec["family"] = (rp.family_profile(mk) or {}).get("family")
        results[mk] = rec
        progress(f"  [{i:2d}/{len(metrics)}] {mk:22s} n={rec.get('n_reference'):4d}  "
                 f"level={rec.get('supported_level'):8s} split={rec.get('split') or '-'}")
    meta = {
        "dataset": nrsa_dataset.MULTI_CYCLE_DATASET_ID,
        "referenceFrame": reference_frame,
        "screen": rscreen.screen_label("strict"),
        "stationScreenSha256": rscreen.station_screen_identity().get("sha256"),
        "valuePolicy": nrsa_dataset.POLICY_LATEST_NON_NULL,
        "nInFrame": int(len(frame)),
        "nReference": int(frame["pass_strict"].astype(bool).sum()),
        "nBoot": int(n_boot), "seed": int(seed),
        "methodologyVersion": methodology.methodology_version(),
    }
    return {"results": results, "inputs": meta, "frame": frame}


def scale_table(results: dict) -> pd.DataFrame:
    rows = []
    for mk, rec in results.items():
        row = {"metric": mk, "display_name": rec.get("display_name"), "family": rec.get("family"),
               "status": rec.get("status"), "n_reference": rec.get("n_reference"),
               "supported_level": rec.get("supported_level")}
        for lvl, t in (rec.get("eta2") or {}).items():
            row[f"{lvl}_eta2_adj"] = t.get("adj")
            row[f"{lvl}_eta2_raw"] = t.get("raw")
            row[f"{lvl}_k"] = t.get("k")
            row[f"{lvl}_n"] = t.get("n")
        rows.append(row)
    return pd.DataFrame(rows)


def split_table(results: dict) -> pd.DataFrame:
    rows = []
    for mk, rec in results.items():
        for key, inc in (rec.get("incremental") or {}).items():
            # only the candidate with the largest increment is tested
            tested = rec.get("split_evaluated") == key
            stab = (rec.get("stability") or {}) if tested else {}
            yard = (rec.get("yardstick") or {}) if tested else {}
            adopted = rec.get("split") == key
            rows.append({
                "metric": mk, "stratifier": key, "increment_adj": inc.get("increment"),
                "combined_adj": inc.get("combined"),
                "n_by_class": json.dumps(inc.get("n_by_class") or {}, sort_keys=True),
                "tested": tested, "adopted": adopted,
                "split_status": rec.get("split_status") if adopted else None,
                "worst_flip_mean": stab.get("worst_flip_mean"),
                "stability": stab.get("verdict"),
                "auc_unsplit": yard.get("auc_unsplit"), "auc_split": yard.get("auc_split"),
                "yardstick": yard.get("verdict")})
    return pd.DataFrame(rows)


def summary_markdown(registry: dict) -> str:
    metrics = registry["metrics"]
    inputs = registry["inputs"]
    rule = registry["rule"]
    by_level: dict[str, list[str]] = {}
    for mk, rec in metrics.items():
        by_level.setdefault(str(rec.get("supported_level")), []).append(mk)
    lines = ["# National scale and stratifier analysis (STRAT-10)", "",
             f"{inputs['nReference']} least-disturbed stations of {inputs['nInFrame']} in the "
             f"{inputs['referenceFrame']} non-canal frame ({inputs['screen']}). Values are the "
             "most recent non-null per metric. Decisions read the bias-adjusted rank "
             "eta-squared.", "",
             f"Rule: a coarser level is supported when it keeps {rule['level_ratio']:g} of the "
             f"Level III value (or sits within {rule['tie']:g} of it). Below "
             f"{rule['national_floor']:g} at Level III the metric is national. A class split "
             f"needs an adjusted increment of {rule['split_incremental_min']:g}, two classes of "
             f"{rule['stratum_min_n']} or more, a resampling flip rate of "
             f"{rule['flip_accept']:g} or less ({rule['flip_exploratory']:g} exploratory), and "
             f"no loss of more than {rule['yardstick_max_auc_loss']:g} in the agreement with "
             f"EPA's reference designation. {inputs['nBoot']} resamples by watershed, seed "
             f"{inputs['seed']}.", "",
             "## Supported level", ""]
    for lvl in ("national", "l1", "l2", "l3"):
        names = by_level.get(lvl) or []
        lines.append(f"- **{LEVEL_WORDS[lvl]}** ({len(names)}): {', '.join(sorted(names)) or 'none'}")
    lines += ["", "| Metric | n reference | Level III | Level II | Level I | NARS-9 | Supported | "
                  "Split |", "|---|---|---|---|---|---|---|---|"]
    for mk, rec in metrics.items():
        eta = rec.get("eta2") or {}

        def cell(lvl):
            t = eta.get(lvl) or {}
            return "" if t.get("adj") is None else f"{t['adj']:.3f} (k {t.get('k')})"
        split = rec.get("split")
        split_txt = f"{split} ({rec.get('split_status')})" if split else ""
        lines.append(f"| {rec.get('display_name')} (`{mk}`) | {rec.get('n_reference')} | "
                     f"{cell('l3')} | {cell('l2')} | {cell('l1')} | {cell('nars9')} | "
                     f"{LEVEL_WORDS.get(str(rec.get('supported_level')), '')} | {split_txt} |")
    lines += ["", "## Class splits considered", ""]
    any_split = False
    for mk, rec in metrics.items():
        for key, inc in (rec.get("incremental") or {}).items():
            if inc.get("increment") is None or inc["increment"] < rule["split_incremental_min"]:
                continue
            any_split = True
            if rec.get("split_evaluated") != key:
                lines.append(f"- `{mk}` by {key}: increment {inc['increment']:.3f}, classes "
                             f"{inc.get('n_by_class')}. Not tested: "
                             f"{rec.get('split_evaluated')} explains more. **not adopted**.")
                continue
            stab, yard = rec.get("stability") or {}, rec.get("yardstick") or {}
            adopted = "adopted" if rec.get("split") == key else "not adopted"
            lines.append(f"- `{mk}` by {key}: increment {inc['increment']:.3f}, classes "
                         f"{inc.get('n_by_class')}, flip rate {stab.get('worst_flip_mean')} "
                         f"({stab.get('verdict')}), yardstick {yard.get('verdict')}. "
                         f"**{adopted}**.")
    if not any_split:
        lines.append("No class split reaches the required increment for any metric.")
    lines += ["", "## Decision basis per metric", ""]
    for mk, rec in metrics.items():
        lines.append(f"- `{mk}`: {rec.get('decision_basis')}")
    return "\n".join(lines) + "\n"


def render(registry: dict) -> str:
    body = yaml.safe_dump(registry, sort_keys=False, allow_unicode=True, width=100,
                          default_flow_style=None)
    return HEADER + "\n" + body


def _plain(obj):
    """YAML-safe plain types (numpy scalars and tuples out)."""
    if isinstance(obj, dict):
        return {str(k): _plain(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_plain(v) for v in obj]
    if hasattr(obj, "item") and not isinstance(obj, (str, bytes)):
        try:
            return obj.item()
        except Exception:  # noqa: BLE001
            return str(obj)
    return obj


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=None, help="evidence folder (tables and a summary page)")
    ap.add_argument("--n-boot", type=int, default=200,
                    help="resamples by watershed for the class-split stability check")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--reference-frame", default="wadeable",
                    choices=nrsa_dataset.REFERENCE_FRAMES)
    ap.add_argument("--metric", action="append", default=None,
                    help="repeatable; analyze only these metrics (never writes the registry)")
    ap.add_argument("--dry-run", action="store_true",
                    help="write the evidence folder but leave the registry file alone")
    ap.add_argument("--check", action="store_true",
                    help="recompute and compare with the committed registry; write nothing")
    ap.add_argument("--decided-on", default=date.today().isoformat())
    a = ap.parse_args(argv)

    if not rscreen.station_screen_available():
        print("data/nrsa/station_screen.parquet is not built; run "
              "scripts/nrsa/build_station_screen.py")
        return 2
    print(f"[scale] analyzing (n_boot {a.n_boot}, seed {a.seed}, frame {a.reference_frame})")
    got = analyze(a.n_boot, a.seed, a.reference_frame, only=set(a.metric) if a.metric else None)
    registry = _plain(sa.build_registry(got["results"], inputs=got["inputs"],
                                        decided_on=a.decided_on))

    if a.check:
        sa.clear_cache()
        have = sa.load_registry()
        same = (have.get("metrics") == registry["metrics"]
                and have.get("rule") == registry["rule"])
        print("[scale] registry: " + ("ok" if same else "STALE (the committed file differs "
                                                        "from what the inputs give today)"))
        return 0 if same else 1

    if a.out:
        out = Path(a.out).resolve()
        out.mkdir(parents=True, exist_ok=True)
        scale_table(got["results"]).to_csv(out / "scale_table.csv", index=False)
        split_table(got["results"]).to_csv(out / "split_table.csv", index=False)
        (out / "registry_summary.md").write_text(summary_markdown(registry), encoding="utf-8")
        (out / "registry_candidate.yaml").write_text(render(registry), encoding="utf-8",
                                                     newline="\n")
        print(f"[scale] evidence -> {out}")

    levels: dict[str, int] = {}
    for rec in registry["metrics"].values():
        levels[str(rec.get("supported_level"))] = levels.get(str(rec.get("supported_level")), 0) + 1
    splits = {mk: rec["split"] for mk, rec in registry["metrics"].items() if rec.get("split")}
    print(f"[scale] supported levels: "
          + ", ".join(f"{LEVEL_WORDS.get(k, k)} {v}" for k, v in sorted(levels.items())))
    print(f"[scale] class splits adopted: {splits or 'none'}")

    if a.metric:
        print("[scale] --metric given: the registry file was not written")
        return 0
    if a.dry_run:
        print("[scale] --dry-run: the registry file was not written")
        return 0
    sa.REGISTRY_PATH.write_text(render(registry), encoding="utf-8", newline="\n")
    sa.clear_cache()
    print(f"[scale] wrote {sa.REGISTRY_PATH.relative_to(APP_ROOT)} "
          f"({sa.registry_sha256()[:19]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
