"""Vendor EASI's reference-curve fit recipe from the national builder, verbatim.

The 34 operational EASI curves were fit by ``tools/easi-national/builder/analysis``: the
quantity definitions, the fit wrapper around StreamCurves' curve engine, the usability rules,
the composite pressure and Spearman's rho of the pressure check, and the rounding the curve
artifact applies. StreamCurves refits from evidence packages with exactly that code, so this
script copies those definitions, source text unchanged, into
``streamcurves/easi_method/fit_recipe.py``. ``tests/test_easi_evidence.py`` fails when the copy
and the builder differ; rerun this script after any change to them.

    python apps/stream-curves/scripts/vendor_fit_recipe.py [--check]
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

APP = Path(__file__).resolve().parents[1]
REPO = APP.parent.parent
BUILDER = REPO / "tools" / "easi-national" / "builder" / "analysis"
TARGET = APP / "streamcurves" / "easi_method" / "fit_recipe.py"

#: (builder module, top-level names in the order they are written)
SOURCES = (
    ("stats.py", ("_ranks", "spearman")),
    ("screens.py", ("ROAD_DENSITY_CAP", "STRICT", "RELAXED", "SCREENS", "FRAME_RULES",
                    "PRESSURE_VARIABLES", "_compare", "evaluate", "composite_pressure")),
    ("panels.py", ("LEVELS", "MIN_STRATUM", "FLOOR_COMPLETE", "FLOOR_EXPLORATORY", "SEED",
                   "MEMBER_COLUMNS", "SCREEN_COLUMNS", "stratum_of", "_thin", "select_panels")),
    ("curves.py", ("INDEX_BANDS", "PRESSURE_RHO_MAX", "SPLIT_FLOOR", "Quantity", "QUANTITIES",
                   "metric_config", "crossings", "fit_curve", "usable")),
    ("artifact.py", ("_rounded", "_curve")),
)

#: The builder's panels code names the screens module (``screens.STRICT``); in one flat file
#: that is a namespace over the screens definitions above it (the only generated code).
SHIMS = {"panels.py": (
    "# (generated) the builder's panels code reads these through its ``screens`` module\n"
    "screens = SimpleNamespace(ROAD_DENSITY_CAP=ROAD_DENSITY_CAP, STRICT=STRICT, RELAXED=RELAXED,\n"
    "                          SCREENS=SCREENS, FRAME_RULES=FRAME_RULES,\n"
    "                          PRESSURE_VARIABLES=PRESSURE_VARIABLES, evaluate=evaluate,\n"
    "                          composite_pressure=composite_pressure)\n")}

HEADER = '''"""EASI's reference-curve fit recipe, vendored verbatim from the national builder.

DO NOT EDIT. Generated by ``scripts/vendor_fit_recipe.py`` from
``tools/easi-national/builder/analysis/{stats,screens,curves,artifact}.py``; the drift test
(``tests/test_easi_evidence.py``) fails when this copy and the builder differ.

What it holds: the least-disturbed screens and the reference panel selection (the seeded
one-per-HUC12 thinning), the fitted quantities, the fit wrapper around StreamCurves' curve
engine (``streamcurves.curves``), the usability rules, the composite pressure and Spearman's
rho of the pressure check, and the six-decimal rounding of the curve artifact. The grouping of
panel members into fits lives in ``refit.py`` and is proven equal to the builder's by refitting
the whole curve registry.
"""
from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from types import SimpleNamespace
from typing import Iterable, Optional

import numpy as np
'''


def segments(path: Path, names) -> list[str]:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
    tree = ast.parse(text)
    found = {}
    for node in tree.body:
        name = None
        if isinstance(node, (ast.FunctionDef, ast.ClassDef, ast.AsyncFunctionDef)):
            name = node.name
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            name = node.target.id
        if name in names:
            start = node.lineno
            if getattr(node, "decorator_list", None):
                start = min(d.lineno for d in node.decorator_list)
            lines = text.splitlines()
            # the comment block directly above a definition belongs to it
            while start > 1 and lines[start - 2].startswith("#"):
                start -= 1
            found[name] = "\n".join(lines[start - 1:node.end_lineno])
    missing = [n for n in names if n not in found]
    if missing:
        raise SystemExit(f"{path.name}: not found: {missing}")
    return [found[n] for n in names]


def render() -> str:
    parts = [HEADER]
    for module, names in SOURCES:
        parts.append(f"\n\n# --- from tools/easi-national/builder/analysis/{module} " + "-" * 20 + "\n")
        if module in SHIMS:
            parts.append(SHIMS[module])
        parts.append("\n\n\n".join(segments(BUILDER / module, names)))
    return "\n".join(parts).rstrip("\n") + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when the copy is out of date")
    a = ap.parse_args(argv)
    if not BUILDER.is_dir():
        raise SystemExit("tools/easi-national is not in this checkout")
    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
    if a.check:
        if current != text:
            print("fit_recipe.py is out of date: run scripts/vendor_fit_recipe.py")
            return 1
        print("fit_recipe.py matches the builder")
        return 0
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
