"""Sync the slim NHDPlus HR reader into site_engine/_hrslim.

``apps/hr-data/hrslim`` owns the slim bundle's format and reader (``tools/hr-slim`` writes the
files with it). The engine carries byte-identical copies of the modules it reads with, so every
vendored app reads the bundle without importing ``apps/`` or ``libs/`` at runtime. Re-run this
after changing those modules; ``tests/test_hrslim_sync.py`` fails on drift.

The package ``__init__.py`` is generated (the source's own imports the version 1 reader's
feature builders the engine does not need). Writes ``HRSLIM_INFO.json`` with the source hashes.

Run from anywhere:  python libs/site_engine/scripts/sync_hrslim.py
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENGINE_ROOT = HERE.parents[0]
REPO = HERE.parents[2]
SRC = REPO / "apps" / "hr-data" / "hrslim"
DEST = ENGINE_ROOT / "site_engine" / "_hrslim"

#: The reader and its helpers (format, grid, shared borders, value and point tables).
MODULES = ("grid.py", "arcs.py", "fmt.py", "fmt2.py", "reader.py", "reader2.py", "lean.py", "values.py",
           "points.py")

INIT = '''"""Slim NHDPlus HR reader, byte-synced from ``apps/hr-data/hrslim`` (generated by
``scripts/sync_hrslim.py``; do not edit). ``site_engine.bundle`` reads the bundle with it."""
'''


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    if not SRC.is_dir():
        print(f"source not found: {SRC}", file=sys.stderr)
        return 1
    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True)
    info = {"synced_from": "apps/hr-data/hrslim", "modules": {}}
    for name in MODULES:
        data = (SRC / name).read_bytes()
        (DEST / name).write_bytes(data)
        info["modules"][name] = _sha(data)
    (DEST / "__init__.py").write_bytes(INIT.encode("utf-8"))
    (DEST / "HRSLIM_INFO.json").write_bytes((json.dumps(info, indent=1) + "\n").encode("utf-8"))
    print(f"synced {len(MODULES)} modules into {DEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
