"""Sync the EASI-canonical modules and data into site_engine/_extracted.

EASI owns the transect machinery (threedep, geomorph, bieger) and the bundled
physio/ecoregion data; the engine carries synced copies so vendored deployments
stay self-contained without fork-and-drift. Re-run this after changing the
sources; ``tests/test_extracts_sync.py`` fails on drift.

Transform rules (deterministic, re-applied by the drift test):
  * ``threedep.py``: ``from .. import geomorph`` -> ``from . import geomorph``
    (both modules live flat in ``_extracted``).
  * ``bieger.py``: unchanged; a generated ``config.py`` shim provides
    ``DATA_DIR`` pointing at ``_extracted/data``.
Writes ``EXTRACTS_INFO.json`` with source + extracted hashes.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ENGINE_ROOT = HERE.parents[0]
REPO = HERE.parents[2]
EASI = REPO / "apps" / "easi"
DEST = ENGINE_ROOT / "site_engine" / "_extracted"

MODULES = {
    "threedep.py": EASI / "easi" / "datasources" / "threedep.py",
    "geomorph.py": EASI / "easi" / "geomorph.py",
    "bieger.py": EASI / "easi" / "bieger.py",
}
DATA_FILES = {
    "physio_divisions.geojson": EASI / "data" / "physio_divisions.geojson",
    "ecoregions_l3.geojson": EASI / "data" / "ecoregions_l3.geojson",
}

CONFIG_SHIM = '''"""Generated by sync_engine_extracts.py — do not edit.

Path shim so the extracted ``bieger.py`` (which does
``from .config import DATA_DIR``) finds the synced data files.
"""
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
'''

INIT = '"""Synced EASI modules + data; see scripts/sync_engine_extracts.py."""\n'


def transform(name: str, text: str) -> str:
    """The deterministic source transform (shared with the drift test)."""
    if name == "threedep.py":
        return text.replace("from .. import geomorph", "from . import geomorph")
    return text


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    manifest: dict = {"modules": {}, "data": {}}
    DEST.mkdir(parents=True, exist_ok=True)
    (DEST / "data").mkdir(exist_ok=True)
    (DEST / "__init__.py").write_text(INIT, encoding="utf-8")
    (DEST / "config.py").write_text(CONFIG_SHIM, encoding="utf-8")
    for name, src in MODULES.items():
        raw = src.read_text(encoding="utf-8")
        out = transform(name, raw)
        (DEST / name).write_text(out, encoding="utf-8")
        manifest["modules"][name] = {
            "source": str(src.relative_to(REPO)).replace("\\", "/"),
            "source_sha": _sha(raw.encode("utf-8")),
            "extracted_sha": _sha(out.encode("utf-8")),
        }
    for name, src in DATA_FILES.items():
        shutil.copyfile(src, DEST / "data" / name)
        manifest["data"][name] = {
            "source": str(src.relative_to(REPO)).replace("\\", "/"),
            "sha": _sha(src.read_bytes()),
        }
    (DEST / "EXTRACTS_INFO.json").write_text(
        json.dumps(manifest, indent=1, sort_keys=True), encoding="utf-8")
    print(f"synced {len(MODULES)} modules + {len(DATA_FILES)} data files "
          f"-> {DEST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
