"""EASI's reference-curve fit recipe, vendored verbatim from the national builder.

DO NOT EDIT. Generated by ``scripts/vendor_fit_recipe.py`` from
``tools/easi-national/builder/analysis/{stats,screens,curves,artifact}.py``; the drift test
(``tests/test_easi_evidence.py``) fails when this copy and the builder differ.

What it holds: the least-disturbed screens and the reference panel selection (the seeded
one-per-HUC12 thinning), the fitted quantities, the fit wrapper around StreamCurves' curve
engine (``streamcurves.curves``), the usability rules, the composite pressure and Spearman's
rho of the pressure check, and the six-decimal rounding of the curve artifact. The grouping of
panel members into fits lives in ``refit.py`` and is proven equal to the builder's by refitting
the whole curve registry.
"""
from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from types import SimpleNamespace
from typing import Iterable, Optional

import numpy as np



# --- from tools/easi-national/builder/analysis/stats.py --------------------

def _ranks(values: np.ndarray) -> np.ndarray:
    """Average ranks (1-based) of a finite array."""
    order = values.argsort(kind="stable")
    sorted_vals = values[order]
    lo = np.searchsorted(sorted_vals, sorted_vals, side="left") + 1
    hi = np.searchsorted(sorted_vals, sorted_vals, side="right")
    ranks = np.empty(len(values), dtype=float)
    ranks[order] = (lo + hi) / 2.0
    return ranks


def spearman(x, y) -> Optional[float]:
    """Spearman's rho over the pairs where both are finite (None under 3 pairs)."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    ok = np.isfinite(x) & np.isfinite(y)
    if ok.sum() < 3:
        return None
    rx, ry = _ranks(x[ok]), _ranks(y[ok])
    rx = rx - rx.mean()
    ry = ry - ry.mean()
    denominator = np.sqrt((rx * rx).sum() * (ry * ry).sum())
    return float((rx * ry).sum() / denominator) if denominator > 0 else None


# --- from tools/easi-national/builder/analysis/screens.py --------------------

#: variable -> (operator, cap); the seven pressure variables of the screen
#: The one documented national cutoff adjustment (plan step 12): with the road
#: cap at 1.0 km/km2 the strict screen passed 29 % of EPA's 2013-14 reference
#: stations nationally and under 50 % in every NARS-9 region (road density was
#: the rule those stations failed most: their median is 0.93 and their 90th
#: percentile 1.95 km/km2). At 2.0 the pass rate is 38 % of reference and 8 %
#: of most-disturbed stations (was 5 %); no other cap changed, and the share of
#: the wadeable non-canal frame passing rises from 26 % to 36 %. Recorded in
#: analysis/nrsa/screen_check_before_road_adjustment.csv.
ROAD_DENSITY_CAP = 2.0


STRICT = {
    "pctimp2019ws": ("<=", 1.0),          # impervious cover, % of the watershed
    "agriculture_ws": ("<=", 10.0),       # crop + hay, %
    "rddensws": ("<=", ROAD_DENSITY_CAP), # road density, km/km2 (see the adjustment above)
    "dor": ("<", 2.0),                    # degree of regulation, %
    "sc__nabd_densws": ("==", 0.0),       # network-snapped dams per km2
    "sc__npdesdensws": ("==", 0.0),       # NPDES outfalls per km2
    "mines_ws": ("==", 0.0),              # mines + coal mines per km2
}


RELAXED = {
    "pctimp2019ws": ("<=", 3.0),
    "agriculture_ws": ("<=", 25.0),
    "rddensws": ("<=", 2.0),
    "dor": ("<", 5.0),
    "sc__npdesdensws": ("==", 0.0),
    "mines_ws": ("==", 0.0),
}


SCREENS = {"strict": STRICT, "relaxed": RELAXED}


#: the frame every panel is drawn from: not a canal, order 1 to 5
FRAME_RULES = {"fcode_class": ("!=", "canal"), "wadeable": ("==", True)}


#: the pressure variables the composite rank averages (the caps' variables)
PRESSURE_VARIABLES = ("pctimp2019ws", "agriculture_ws", "rddensws", "dor", "sc__npdesdensws", "mines_ws",
                      "corridor_conversion_wsrp100")


def _compare(values, operator: str, cap) -> np.ndarray:
    if operator == "<=":
        return values <= cap
    if operator == "<":
        return values < cap
    if operator == "==":
        return values == cap
    if operator == "!=":
        return values != cap
    raise ValueError(f"unknown operator {operator!r}")


def evaluate(columns: dict, rules: dict, *, missing: str = "skip") -> tuple[np.ndarray, list[str]]:
    """``(mask, skipped)``: True where every available rule holds (a missing
    numeric value fails its rule); ``skipped`` names the rule variables the
    table lacks. ``missing="fail"`` raises on a missing variable instead."""
    mask = None
    skipped: list[str] = []
    for name, (operator, cap) in rules.items():
        if name not in columns:
            if missing == "fail":
                raise KeyError(f"screen variable {name!r} is not in the table")
            skipped.append(name)
            continue
        values = np.asarray(columns[name])
        if values.dtype.kind in "fiu":
            values = np.asarray(values, dtype=float)
            ok = np.isfinite(values) & _compare(values, operator, cap)
        else:
            ok = _compare(values.astype(object), operator, cap)
        mask = ok if mask is None else (mask & ok)
    if mask is None:
        mask = np.ones(len(next(iter(columns.values()))) if columns else 0, dtype=bool)
    return np.asarray(mask, dtype=bool), skipped


def composite_pressure(columns: dict, variables: Iterable[str] = PRESSURE_VARIABLES) -> tuple[np.ndarray, list[str]]:
    """The mean percentile rank (0 to 1, higher is more pressure) over the
    pressure variables present; NaN where every variable is missing."""
    ranks = []
    used = []
    n = None
    for name in variables:
        if name not in columns:
            continue
        values = np.asarray(columns[name], dtype=float)
        n = len(values)
        finite = np.isfinite(values)
        rank = np.full(n, np.nan)
        if finite.any():
            order = values[finite].argsort(kind="stable")
            r = np.empty(finite.sum())
            r[order] = np.arange(1, finite.sum() + 1)
            # average ties by ranking the sorted values against themselves
            sorted_vals = values[finite][order]
            lo = np.searchsorted(sorted_vals, sorted_vals, side="left") + 1
            hi = np.searchsorted(sorted_vals, sorted_vals, side="right")
            avg = np.empty_like(r)
            avg[order] = (lo + hi) / 2.0
            rank[finite] = (avg - 0.5) / finite.sum()
        ranks.append(rank)
        used.append(name)
    if not ranks:
        return np.full(n or 0, np.nan), used
    stacked = np.vstack(ranks)
    with np.errstate(invalid="ignore"):
        return np.nanmean(stacked, axis=0), used


# --- from tools/easi-national/builder/analysis/panels.py --------------------

# (generated) the builder's panels code reads these through its ``screens`` module
screens = SimpleNamespace(ROAD_DENSITY_CAP=ROAD_DENSITY_CAP, STRICT=STRICT, RELAXED=RELAXED,
                          SCREENS=SCREENS, FRAME_RULES=FRAME_RULES,
                          PRESSURE_VARIABLES=PRESSURE_VARIABLES, evaluate=evaluate,
                          composite_pressure=composite_pressure)

LEVELS = ("l3", "l2", "l1", "nars9", "national")


#: a stratum needs this many reaches to be a stratum at all
MIN_STRATUM = 1000


FLOOR_COMPLETE = 100


FLOOR_EXPLORATORY = 30


SEED = 7


#: columns the members table keeps (the curve fitting groups on the splits)
MEMBER_COLUMNS = ("comid", "huc12", "state", "slope_class", "fcode_class", "da_class", "in_scored_set",
                  "totdasqkm", "streamorde")


SCREEN_COLUMNS = tuple(sorted({*screens.STRICT, *screens.RELAXED, *screens.FRAME_RULES, *screens.PRESSURE_VARIABLES}))


def stratum_of(frame, level: str):
    """The stratum code per row for a level (``national`` is one stratum)."""
    import pandas as pd
    if level == "national":
        return pd.Series(["national"] * len(frame), index=frame.index, dtype="object")
    column = level
    if column not in frame.columns:
        raise KeyError(f"level {level!r} has no column in the landscape table")
    return frame[column].astype("object").where(frame[column].notna(), None)


def _thin(candidates, stratum, seed: int):
    """One reach per (stratum, HUC12) among the candidate rows, chosen by a
    seeded random key so the choice is reproducible."""
    import pandas as pd
    if len(candidates) == 0:
        return candidates
    rng = np.random.default_rng(seed)
    keyed = candidates.assign(_stratum=stratum.loc[candidates.index].to_numpy(),
                              _key=rng.random(len(candidates)))
    keyed = keyed.sort_values(["_stratum", "huc12", "_key"], kind="stable")
    thinned = keyed.drop_duplicates(["_stratum", "huc12"], keep="first")
    return thinned.drop(columns=["_key"])


def select_panels(frame, level: str, *, seed: int = SEED, min_stratum: int = MIN_STRATUM):
    """``(panels, members)`` for one level over a landscape frame (pandas)."""
    import pandas as pd
    stratum = stratum_of(frame, level)
    has = stratum.notna()
    columns = {name: frame[name].to_numpy() for name in SCREEN_COLUMNS if name in frame.columns}
    in_frame, skipped_frame = screens.evaluate(columns, screens.FRAME_RULES)
    strict, skipped_strict = screens.evaluate(columns, screens.STRICT)
    relaxed, skipped_relaxed = screens.evaluate(columns, screens.RELAXED)
    strict = in_frame & strict & has.to_numpy()
    relaxed = in_frame & relaxed & has.to_numpy()
    keep = [c for c in MEMBER_COLUMNS if c in frame.columns]
    thinned_strict = _thin(frame.loc[strict, keep], stratum, seed)
    thinned_relaxed = _thin(frame.loc[relaxed, keep], stratum, seed + 1)
    totals = stratum[has].value_counts()
    frame_counts = stratum[has & pd.Series(in_frame, index=frame.index)].value_counts()
    strict_counts = stratum[pd.Series(strict, index=frame.index)].value_counts()
    relaxed_counts = stratum[pd.Series(relaxed, index=frame.index)].value_counts()
    thinned_strict_counts = thinned_strict["_stratum"].value_counts() if len(thinned_strict) else pd.Series(dtype=int)
    thinned_relaxed_counts = thinned_relaxed["_stratum"].value_counts() if len(thinned_relaxed) else pd.Series(dtype=int)
    rows = []
    member_frames = []
    for code in sorted(totals.index, key=lambda c: (len(str(c)), str(c))):
        n_total = int(totals.get(code, 0))
        n_strict = int(thinned_strict_counts.get(code, 0))
        n_relaxed = int(thinned_relaxed_counts.get(code, 0))
        if n_total < min_stratum:
            screen_used, tier, reason = "none", "none", f"stratum under {min_stratum} reaches"
        elif n_strict >= FLOOR_EXPLORATORY:
            screen_used = "strict"
            tier = "complete" if n_strict >= FLOOR_COMPLETE else "exploratory"
            reason = ""
        elif n_relaxed >= FLOOR_EXPLORATORY:
            screen_used, tier, reason = "relaxed", "best_available", "strict panel under 30 reaches"
        else:
            screen_used, tier, reason = "none", "none", "no panel of 30 reaches under either screen"
        members = None
        if screen_used == "strict":
            members = thinned_strict[thinned_strict["_stratum"] == code]
        elif screen_used == "relaxed":
            members = thinned_relaxed[thinned_relaxed["_stratum"] == code]
        n_ref = int(len(members)) if members is not None else 0
        da = members["totdasqkm"].to_numpy(dtype=float) if members is not None and "totdasqkm" in members else np.zeros(0)
        da = da[np.isfinite(da)]
        states = (members["state"].value_counts().head(5).to_dict() if members is not None and "state" in members else {})
        rows.append({
            "level": level, "stratum": f"{level}:{code}", "code": str(code), "n_total": n_total,
            "n_frame": int(frame_counts.get(code, 0)), "n_pass_strict": int(strict_counts.get(code, 0)),
            "n_pass_relaxed": int(relaxed_counts.get(code, 0)), "n_strict_thinned": n_strict,
            "n_relaxed_thinned": n_relaxed, "n_ref": n_ref, "screen": screen_used, "panel_tier": tier,
            "reason": reason, "skipped_rules": ";".join(sorted(set(skipped_frame + skipped_strict + skipped_relaxed))),
            "n_ref_scored": int(members["in_scored_set"].sum()) if members is not None and "in_scored_set" in members else 0,
            "da_p25": float(np.quantile(da, 0.25)) if da.size else None,
            "da_p50": float(np.quantile(da, 0.5)) if da.size else None,
            "da_p75": float(np.quantile(da, 0.75)) if da.size else None,
            "states": json.dumps({str(k): int(v) for k, v in states.items()}),
        })
        if members is not None and len(members):
            member_frames.append(members.assign(level=level, stratum=f"{level}:{code}", screen=screen_used,
                                                panel_tier=tier).drop(columns=["_stratum"]))
    panels = pd.DataFrame(rows)
    members_out = (pd.concat(member_frames, ignore_index=True) if member_frames
                   else pd.DataFrame(columns=[*keep, "level", "stratum", "screen", "panel_tier"]))
    return panels, members_out


# --- from tools/easi-national/builder/analysis/curves.py --------------------

INDEX_BANDS = (0.39, 0.69)


PRESSURE_RHO_MAX = 0.30


SPLIT_FLOOR = 30


@dataclass(frozen=True)
class Quantity:
    key: str
    source: str                      # landscape | values
    column: str
    higher_is_better: bool
    domain: tuple = (None, None)
    functions: tuple = ()
    kind: str = "incumbent"          # incumbent | candidate
    zero_inflated: bool = False
    geometry: bool = False           # fitted at national x slope class (never by ecoregion)
    split: Optional[str] = None      # a secondary split column (slope_class, fcode_class)
    cap: Optional[float] = None      # right-censoring cap (the bank-height ratio's 2.0)
    gate: Optional[tuple] = None     # (column, minimum) rows the quantity is defined for
    label: str = ""


QUANTITIES: dict[str, Quantity] = {q.key: q for q in (
    Quantity("wetland_ws", "landscape", "wetland_ws", True, (0.0, 100.0), ("surface_water_storage",),
             zero_inflated=True, label="Wetland cover in the watershed, %"),
    Quantity("wetland_retention", "landscape", "wetland_retention", True, (0.0, None), ("surface_water_storage",),
             kind="candidate", gate=("sc__pcthydricws", 5.0), label="Wetland cover over hydric soils"),
    Quantity("woody_wsrp100", "landscape", "woody_wsrp100", True, (0.0, 100.0),
             ("light_thermal_regime", "habitat_provision"), label="Woody riparian cover, watershed corridor, %"),
    Quantity("natural_wsrp100", "landscape", "natural_wsrp100", True, (0.0, 100.0), ("carbon_processing",),
             label="Natural riparian vegetation, watershed corridor, %"),
    Quantity("woody_catrp100", "landscape", "woody_catrp100", True, (0.0, 100.0), ("light_thermal_regime",),
             kind="candidate", label="Woody riparian cover, reach corridor, %"),
    Quantity("natural_catrp100", "landscape", "natural_catrp100", True, (0.0, 100.0), ("carbon_processing",),
             kind="candidate", label="Natural riparian vegetation, reach corridor, %"),
    Quantity("bfiws", "landscape", "sc__bfiws", True, (0.0, 100.0), ("low_flow_baseflow_dynamics",),
             kind="candidate", split="fcode_class", label="Base flow index, %"),
    Quantity("q_min_ratio", "landscape", "erom__q_min_ratio", True, (0.0, 1.0), ("low_flow_baseflow_dynamics",),
             kind="candidate", split="fcode_class", label="Minimum monthly over mean annual flow"),
    Quantity("q_cv_monthly", "landscape", "erom__q_cv_monthly", False, (0.0, None), ("streamflow_regime",),
             kind="candidate", label="Monthly flow variability (CV)"),
    Quantity("hyd_min", "landscape", "hyd_min", True, (0.0, 1.0), ("low_flow_baseflow_dynamics",),
             label="HYD integrity, min of catchment and watershed"),
    Quantity("sed_min", "landscape", "sed_min", True, (0.0, 1.0), ("bed_composition_bedform_dynamics",),
             label="SED integrity, min of catchment and watershed"),
    Quantity("chem_min", "landscape", "chem_min", True, (0.0, 1.0), ("nutrient_cycling", "water_soil_quality"),
             label="CHEM integrity, min of catchment and watershed"),
    Quantity("habt_min", "landscape", "habt_min", True, (0.0, 1.0), ("habitat_provision",),
             kind="candidate", label="HABT integrity, min of catchment and watershed"),
    Quantity("prg_bmmi0809", "landscape", "sc__prg_bmmi0809", True, (0.0, 1.0), ("population_support",),
             kind="candidate", label="Predicted probability of good benthic condition"),
    Quantity("er_median", "values", "er_median", True, (0.0, None), ("floodplain_connectivity", "channel_evolution"),
             geometry=True, label="Entrenchment ratio, reach median"),
    Quantity("bhr_median", "values", "bhr_median", False, (0.0, 2.0),
             ("high_flow_dynamics", "channel_floodplain_dynamics", "channel_evolution"),
             geometry=True, cap=2.0, label="Bank-height ratio, reach median"),
    Quantity("bhr_share_ge_1p5", "values", "bhr_share_ge_1p5", False, (0.0, 1.0), ("high_flow_dynamics",),
             kind="candidate", geometry=True, label="Share of transects with bank-height ratio >= 1.5"),
    Quantity("sinuosity_flowline", "landscape", "sinuosity_flowline", True, (1.0, None),
             ("channel_floodplain_dynamics", "hyporheic_connectivity"), kind="candidate", geometry=True,
             label="Flowline sinuosity"),
    Quantity("bankfull_width_cv", "values", "bankfull_width_cv", True, (0.0, None), ("habitat_provision",),
             kind="candidate", geometry=True, label="Bankfull width variability across transects (CV)"),
    Quantity("bankfull_depth_cv", "values", "bankfull_depth_cv", True, (0.0, None), ("habitat_provision",),
             kind="candidate", geometry=True, label="Bankfull depth variability across transects (CV)"),
    Quantity("tn", "values", "v__nutrient_cycling__tn", False, (0.0, None), ("nutrient_cycling",),
             label="Total nitrogen, WQP median, mg/L"),
    Quantity("tp", "values", "v__nutrient_cycling__tp", False, (0.0, None), ("nutrient_cycling",),
             label="Total phosphorus, WQP median, mg/L"),
)}


# ------------------------------------------------------------ fitting
def metric_config(q: Quantity) -> dict:
    return {q.key: {"column_name": q.column, "higher_is_better": q.higher_is_better, "curve_form": "monotone",
                    "domain_min": q.domain[0], "domain_max": q.domain[1], "signed_scale": False,
                    "display_name": q.label or q.key}}


def crossings(points, target: float) -> list[float]:
    from streamcurves import curves as engine
    return engine.reference_curve_threshold_crossings(points, target)


def fit_curve(values, q: Quantity, stratum: str) -> dict:
    """One fit: the engine's status, stats, points and the two class crossings."""
    import pandas as pd
    from streamcurves import curves as engine
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    result = engine.build_reference_curve(pd.DataFrame({q.column: arr}), q.key, metric_config(q),
                                          stratum_label=stratum, build_plots=False)
    row = result["curve_row"]
    points = result["curve_points"]
    status = str(row["curve_status"].iloc[0])
    out = {
        "status": status,
        "n": int(arr.size),
        "q05": float(np.quantile(arr, 0.05)) if arr.size else None,
        "q25": float(row["q25"].iloc[0]) if arr.size else None,
        "q50": float(row["median_val"].iloc[0]) if arr.size else None,
        "q75": float(row["q75"].iloc[0]) if arr.size else None,
        "q95": float(np.quantile(arr, 0.95)) if arr.size else None,
        "iqr": float(row["iqr"].iloc[0]) if arr.size else None,
        "min": float(row["min_val"].iloc[0]) if arr.size else None,
        "max": float(row["max_val"].iloc[0]) if arr.size else None,
        "points": [[float(x), float(y)] for x, y in zip(points["metric_value"], points["index_score"])],
        "x39": None, "x69": None,
    }
    if len(points) >= 2:
        lo = crossings(points, INDEX_BANDS[0])
        hi = crossings(points, INDEX_BANDS[1])
        out["x39"] = lo[0] if len(lo) == 1 else None
        out["x69"] = hi[0] if len(hi) == 1 else None
    return out


def usable(q: Quantity, row: dict, tier: str) -> tuple[bool, str]:
    if tier == "none":
        return False, "no panel at this level"
    if row.get("status") != "complete":
        return False, f"engine status {row.get('status')}"
    if row.get("x39") is None or row.get("x69") is None:
        return False, "missing a class crossing"
    if q.zero_inflated and (row.get("q25") or 0) <= 0:
        return False, "zero-inflated: panel first quartile is zero"
    if q.cap is not None:
        # a right-censored panel: its upper quartile sits at the cap, so the engine's domain
        # clamp squeezes the seed and every crossing is an artefact of the cap
        quartile = row.get("q75") if not q.higher_is_better else row.get("q25")
        edge = row["x39"] if not q.higher_is_better else row["x69"]
        if (quartile is not None and quartile >= q.cap - 1e-9) or edge >= q.cap - 1e-9:
            return False, f"censored at the {q.cap} cap"
    rho = row.get("rho_pressure")
    if rho is not None and abs(rho) > PRESSURE_RHO_MAX:
        if tier == "best_available":
            return False, f"pressure-driven inside a relaxed panel (rho {rho:.2f})"
        return True, f"pressure-driven inside the panel (rho {rho:.2f}), strict tier only"
    return True, ""


# --- from tools/easi-national/builder/analysis/artifact.py --------------------

def _rounded(value):
    """Canonical JSON values, including six-place finite floats."""
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("Reference artifact contains a non-finite number")
        rounded = round(value, 6)
        return 0.0 if rounded == 0 else rounded
    if isinstance(value, dict):
        return {key: _rounded(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_rounded(item) for item in value]
    return value


def _curve(row: dict) -> dict:
    points = row.get("points")
    if points is None:
        points = json.loads(row.get("points_json") or "[]")
    if len(points) < 2:
        raise ValueError(f"Usable curve has no point list: {row.get('quantity')}")
    numeric = {key: float(row[key]) for key in ("q25", "q50", "q75", "x39", "x69")}
    return _rounded({
        "points": [[float(x), float(y)] for x, y in points],
        "n": int(row["n"]),
        "nMembers": int(row["n_members"]),
        **numeric,
        "status": row["status"],
        "panelTier": row["panel_tier"],
        "screen": row["screen"],
    })
