"""Generated by sync_engine_extracts.py — do not edit.

Path shim so the extracted ``bieger.py`` (which does
``from .config import DATA_DIR``) finds the synced data files.
"""
from pathlib import Path

DATA_DIR = Path(__file__).parent / "data"
