"""The EASI Excel calculator, blank and completed.

The workbook under ``www/calculator/`` is generated by ``scripts/build_calculator.py``
from the same scoring definitions the application uses (catalog, reference
curves, weights, anchors). It is a deliverable of the methodology, so the blank
is handed out byte for byte and ``tests/test_calculator_parity.py`` proves the
workbook scores like the engine.

The completed copy is that same workbook with a screening typed into its entry
cells: the values the engine actually rated (read from each row's scoring
trace, already rounded the way the adapters round them), the site block, the
ratings changed on the Assessment page (the workbook's Override Score entries,
one under every function), and the assessor's notes.
Nothing else differs from the blank, so a completed workbook recalculates to
the application's own ratings, scores and indices when Excel opens it.

openpyxl cannot do this: a load and save drops the charts, and it is not a
runtime dependency. So, like ``apps/sfari/sfari/calculator.py``, this edits the
worksheet XML inside the zip and copies every other part through untouched.
``zipfile`` and ``re`` are enough. Nothing is read at import (the copy vendored
into StreamCurves has no ``www/``).
"""
from __future__ import annotations

import copy
import datetime as _dt
import io
import math
import numbers
import re
import zipfile
from functools import lru_cache
from pathlib import Path

#: The committed calculator. Part of the filename so a returned workbook can be
#: traced to the release it came from. ``scripts/build_calculator.py`` reads the
#: version from here, so the generator and the served file cannot disagree.
TEMPLATE_VERSION = "1.0"

TEMPLATE_PATH = (Path(__file__).resolve().parent.parent
                 / "www" / "calculator" / f"EASI_Calculator_{TEMPLATE_VERSION}.xlsx")

SHEET_NAME = "EASI Score"
ENTRY_PREFIXES = ("in_", "ctx_", "ov_", "site_")
NOTES_NAME = "site_notes"
NOTES_LABEL = "Other Metrics/Notes:"
#: The notes box is ten rows tall and a merged cell does not grow, so the text is
#: kept to what a reader can reach; the desktop metrics PDF carries the rest.
NOTES_LIMIT = 1500
NOTES_CONTINUED = " (continued in the desktop metrics PDF)"

#: Keys that name the same quantity under two catalog names. A copy of
#: ``scripts/build_calculator.py`` ALIASES (``scripts/`` is not deployed);
#: ``tests/test_calculator_fill.py`` keeps the two equal.
ALIASES = {"chemCat": "chemCatchment", "chemWs": "chemWatershed"}

#: Traced inputs that are context for a rating and have no entry cell of their own.
_CONTEXT_KEYS = {"fcode", "fcodeContext", "meanAnnualFlow", "annualRetreatContext"}
_FCODE_KEYS = ("fcode", "fcodeContext")
VALID = ("Good", "Fair", "Poor")

#: Excel's day zero for the 1900 date system. 1899-12-30 rather than 1899-12-31
#: because it absorbs the phantom 1900-02-29 for every date from 1900-03-01 on.
_EXCEL_EPOCH = _dt.date(1899, 12, 30)


# --- The blank ----------------------------------------------------------------
@lru_cache(maxsize=1)
def blank_bytes() -> bytes:
    """The committed workbook, read once.

    Bytes, not an open ``ZipFile``: handing a live archive's ``ZipInfo`` to
    ``writestr`` mutates it, which would corrupt a cached archive.
    """
    return TEMPLATE_PATH.read_bytes()


def blank_filename() -> str:
    return TEMPLATE_PATH.name


@lru_cache(maxsize=1)
def entry_cells() -> dict[str, str]:
    """Entry name -> cell on the EASI Score sheet, from the workbook's own defined names.

    The generator names every entry cell (``in_``, ``ctx_``, ``ov_``, ``site_``),
    so no cell map is kept here and a regenerated workbook whose rows moved is
    filled correctly without an edit.
    """
    with zipfile.ZipFile(io.BytesIO(blank_bytes())) as archive:
        book = archive.read("xl/workbook.xml").decode("utf-8")
    cells: dict[str, str] = {}
    for name, target in re.findall(r'<definedName\b[^>]*\bname="([^"]+)"[^>]*>([^<]*)</definedName>', book):
        if not name.startswith(ENTRY_PREFIXES):
            continue
        sheet, _, addr = _xml_unescape(target).rpartition("!")
        if sheet.strip("'") != SHEET_NAME:
            raise ValueError(f"EASI calculator entry {name} is not on the {SHEET_NAME} sheet")
        cells[name] = addr.replace("$", "")
    if NOTES_NAME not in cells:
        raise ValueError("EASI calculator template has no entry cells")
    return cells


# --- Entries from a screening ---------------------------------------------------
def monthly_flows(erom) -> list[float] | None:
    """The twelve EROM mean monthly flows (``qe_01`` .. ``qe_12``) as a list, or None.

    All twelve or nothing: the workbook's helper computes the variability only from a
    full year, exactly as ``metrics.hydraulics.monthly_flow_cv`` does, so a partial
    year would only leave a helper that shows no result beside an entered one.
    """
    if not isinstance(erom, dict):
        return None
    flows = []
    for month in range(1, 13):
        value = erom.get(f"qe_{month:02d}")
        if isinstance(value, bool) or not isinstance(value, numbers.Real) or not math.isfinite(float(value)):
            return None
        flows.append(float(value))
    return flows


def _catalog_rows(report: dict) -> list[tuple[str, dict]]:
    """``(mNN, row)`` in catalog order, the order of the workbook's rows."""
    from . import config

    by_id = {row.get("metricId"): row for row in report.get("metricRows") or []}
    return [(f"m{n:02d}", by_id[mid]) for n, mid in enumerate(config.metrics_by_id(), 1) if mid in by_id]


def _same_value(a, b) -> bool:
    if isinstance(a, numbers.Real) and isinstance(b, numbers.Real):
        return math.isclose(float(a), float(b), rel_tol=0.0, abs_tol=1e-12)
    return str(a) == str(b)


def _text(value) -> str:
    """A traced value for a sentence."""
    if isinstance(value, numbers.Real) and not isinstance(value, bool):
        return _number_text(value) or str(value)
    return str(value)


def entries_from_result(result: dict) -> tuple[dict, list[str]]:
    """Calculator entries for a screening, and what a reader should know about them.

    ``result`` is the application's result dict (``delineation``, ``report``,
    ``siteAnchor``): ``export_result()`` for a single site, a batch site's
    ``_artifacts``. Returns ``({entry name: value}, disclosure lines)``.

    Report driven and never raises. Every quantity is the value the engine rated
    with, taken from the scoring trace of the method that rated the row. An entry
    only another route would read stays blank, which leaves the workbook on the
    route the application took. One cell serves every function that reads a
    quantity, so rows are read in the order that makes the cell agree with the
    ratings on screen: rows re-rated from an edited or scrolled cross-section
    first, then the other computed rows, then rows the assessor re-rated (their
    trace is the one the rating replaced).
    """
    result = result or {}
    report = result.get("report") or {}
    cells = entry_cells()
    entries: dict = {}
    origin: dict[str, str] = {}
    disclosures: list[str] = []
    unknown: set[str] = set()
    fcode = None

    ordered = _catalog_rows(report)
    rank = {"xs-derived": 0, "override": 2}
    ordered_for_values = sorted(ordered, key=lambda item: rank.get(item[1].get("status"), 1))  # stable
    for mkey, row in ordered_for_values:
        function = row.get("functionName") or row.get("name") or mkey
        for item in (row.get("scoring") or {}).get("inputs") or []:
            key = ALIASES.get(item.get("key"), item.get("key"))
            value = item.get("value")
            if key is None or value is None or value == "":
                continue
            if key in _FCODE_KEYS:
                fcode = fcode if fcode is not None else value
                continue
            name = f"in_{key}" if f"in_{key}" in cells else f"ov_{key}" if f"ov_{key}" in cells else None
            if name is None:
                if key not in _CONTEXT_KEYS and not item.get("contextOnly"):
                    unknown.add(str(item.get("label") or key))
                continue
            if name not in entries:
                entries[name], origin[name] = value, function
            elif not _same_value(entries[name], value):
                disclosures.append(
                    f"{item.get('label') or key}: the workbook holds {_text(entries[name])} (from {origin[name]}); "
                    f"the application rated {function} with {_text(value)}.")

    # context
    strata = report.get("strata") or {}
    if strata.get("nars9"):
        entries["ctx_region"] = str(strata["nars9"])
    if fcode is None:
        fcode = ((report.get("crossSection") or {}).get("geom") or {}).get("fcode")
    if fcode is None:
        fcode = (result.get("delineation") or {}).get("fcode")
    try:
        # a number: as text the workbook's canal test never matches and the route is lost
        entries["ctx_fcode"] = int(float(fcode))
    except (TypeError, ValueError):
        pass
    if "slope_class" in strata:
        from . import geo

        used = strata.get("slope_class") or "national"
        if (geo.slope_class(entries.get("in_slope")) or "national") != used:
            entries["ctx_slope_override"] = used

    # the monthly flow helper: the twelve flows behind the variability entered above, when
    # the result kept them (the application does, as ``eromMonthly``). The helper is not
    # linked to the entry, so this only lets a reader see where the entered value came from.
    flows = result.get("eromMonthly")
    if (isinstance(flows, (list, tuple)) and len(flows) == 12 and "in_flowCv" in entries
            and all(_number_text(v) is not None for v in flows)):      # a full year or nothing
        for month, value in enumerate(flows, 1):
            if f"in_m{month:02d}" in cells:
                entries[f"in_m{month:02d}"] = value

    # the override scores (every function has the entry, as every function card of the
    # Assessment page has the rating select), and what the application left unrated
    assessed, unrated = [], []
    for mkey, row in ordered:
        function = row.get("functionName") or row.get("name") or mkey
        rating = row.get("rating")
        if row.get("status") == "override" and rating in VALID:
            name = f"ov_{mkey}_rating"
            computed = (row.get("effectiveOverride") or {}).get("generatedRating") or "not rated"
            if name in cells:
                entries[name] = rating
                assessed.append(f"{function} {rating} (computed {computed})")
            else:       # a workbook without the entry: say so rather than drop the override silently
                disclosures.append(f"{function}: the application's rating {rating} is a user override, and "
                                   "this workbook has no Override Score entry for the function.")
        elif rating not in VALID and row.get("status") != "excluded":
            unrated.append(function)
    if assessed:
        disclosures.insert(0, "Override scores: " + "; ".join(assessed) + ".")
    if unrated:
        disclosures.append("Not rated by the application: " + ", ".join(unrated) + ". The workbook rates a "
                           "function whenever its entries are present.")
    if unknown:
        disclosures.append("Not entered (no cell in this workbook): " + ", ".join(sorted(unknown)) + ".")

    # the site block
    site = site_identity(result)
    if site["label"]:
        entries["site_name"] = site["label"]
    if site["comid"]:
        entries["site_comid"] = site["comid"]
    if site["coords"]:
        entries["site_coords"] = site["coords"]
    return entries, disclosures


def site_identity(result: dict) -> dict:
    """The stream, its reach identifier and the analysis point, as the site block shows them."""
    result = result or {}
    d = result.get("delineation") or {}
    anchor = result.get("siteAnchor") or {}
    clicked = anchor.get("clickedStream") or {}
    routed = anchor.get("anchorKind") == "hrSurrogate"
    name = (clicked.get("gnisName") if routed else d.get("gnis_name")) or ""
    comid = d.get("comid")
    comid = "" if comid in (None, "", "None") else str(comid)
    if routed and clicked.get("nhdplusId") not in (None, "", "None"):
        reach = f"NHDPlusID {clicked['nhdplusId']}"
    else:
        reach = f"COMID {comid}" if comid else ""
    lat, lon = d.get("snapped_lat"), d.get("snapped_lon")
    try:
        coords = f"{float(lat):.5f}, {float(lon):.5f}"
    except (TypeError, ValueError):
        coords = ""
    label = ", ".join(part for part in ((name or ("Unnamed stream" if reach else "")), reach) if part)
    return {"name": name, "reach": reach, "comid": comid, "coords": coords, "label": label}


def notes_text(result: dict, disclosures: list[str], today: _dt.date) -> str:
    """The notes box: the template's label, where the entries came from, and the assessor's notes."""
    report = (result or {}).get("report") or {}
    site = site_identity(result)
    where = " from the screening of " + site["label"] if site["label"] else ""
    lines = [NOTES_LABEL,
             f"Completed by the EASI web application on {today.isoformat()}{where}."]
    lines.extend(disclosures)
    notes = [f"{row.get('functionName') or mkey}: {' '.join(str(row['userNote']).split())}"
             for mkey, row in _catalog_rows(report) if str(row.get("userNote") or "").strip()]
    if notes:
        lines.append("Assessor notes. " + " | ".join(notes))
    text = "\n".join(lines)
    if len(text) > NOTES_LIMIT:
        text = text[:NOTES_LIMIT - len(NOTES_CONTINUED)].rstrip() + NOTES_CONTINUED
    return text


# --- Cell writing ---------------------------------------------------------------
_ILLEGAL_XML = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f]")
# An empty cell is <c .../> without lxml and <c ...></c> with it; both must fill.
_CELL_RE = re.compile(r'<c r="([A-Z]+[0-9]+)"((?:\s+[A-Za-z:]+="[^"]*")*)\s*(?:/>|>(.*?)</c>)', re.S)
_TYPE_ATTR = re.compile(r'\s+t="[^"]*"')


def _xml_unescape(text: str) -> str:
    from xml.sax.saxutils import unescape

    return unescape(text, {"&apos;": "'", "&quot;": '"'})


def _xml_text(value) -> str:
    """Escape for an XML text node, including what Excel's own escape covers."""
    text = _ILLEGAL_XML.sub("", str(value))
    # Excel decodes _xHHHH_ on read, so a literal one in user text has to be
    # escaped or it comes back as a different character.
    text = re.sub(r"_(x[0-9A-Fa-f]{4}_)", r"_x005F_\1", text)
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _number_text(value) -> str | None:
    """A number the way the sheet XML carries it, or None when it is not one.

    ``float()`` first: ``repr`` of a numpy scalar is ``np.float64(...)``. Whole
    values print without a decimal (a feature code is 33600, not 33600.0).
    """
    if isinstance(value, bool) or not isinstance(value, numbers.Real):
        return None
    number = float(value)
    if not math.isfinite(number):
        return None
    if number.is_integer() and abs(number) < 1e15:
        return str(int(number))
    return repr(number)


def _excel_serial(day: _dt.date) -> int:
    return (day - _EXCEL_EPOCH).days


def _fill_cells(sheet_xml: str, values: dict, *, notes_ref: str | None = None) -> str:
    """Replace each empty cell named in ``values`` with the same cell carrying it.

    One pass, and the refs actually replaced are checked against the refs
    intended: a workbook whose cells moved, or that already holds something in an
    entry cell, fails here rather than coming back silently wrong. The notes cell
    is the one entry that ships with text (its label), which the new text keeps
    as its first line.
    """
    seen: set[str] = set()

    def repl(m: re.Match) -> str:
        ref, attrs, content = m.group(1), m.group(2), m.group(3)
        if ref not in values:
            return m.group(0)
        if content and not (ref == notes_ref and _xml_text(NOTES_LABEL) in content):
            raise ValueError(f"EASI calculator entry cell {ref} is not empty in the template")
        seen.add(ref)
        value = values[ref]
        attrs = _TYPE_ATTR.sub("", attrs)
        number = _number_text(value)
        if number is not None:
            return f'<c r="{ref}"{attrs} t="n"><v>{number}</v></c>'
        return (f'<c r="{ref}"{attrs} t="inlineStr"><is><t xml:space="preserve">'
                f'{_xml_text(value)}</t></is></c>')

    out = _CELL_RE.sub(repl, sheet_xml)
    missing = set(values) - seen
    if missing:
        raise ValueError("EASI calculator template does not carry the expected entry cells: "
                         + ", ".join(sorted(missing)))
    return out


def _sheet_part(archive: zipfile.ZipFile, name: str) -> str:
    """The worksheet part for a sheet name, resolved through the rels."""
    book = archive.read("xl/workbook.xml").decode("utf-8")
    rid = None
    for tag in re.findall(r"<sheet\b[^>]*/>", book):
        got = re.search(r'name="([^"]*)"', tag)
        if got and _xml_unescape(got.group(1)) == name:
            found = re.search(r'r:id="([^"]*)"', tag)
            rid = found.group(1) if found else None
            break
    if not rid:
        raise ValueError(f"EASI calculator template has no sheet named {name!r}")
    rels = archive.read("xl/_rels/workbook.xml.rels").decode("utf-8")
    target = None
    for tag in re.findall(r"<Relationship\b[^>]*/>", rels):
        if re.search(r'\bId="%s"' % re.escape(rid), tag):
            found = re.search(r'\bTarget="([^"]*)"', tag)
            target = found.group(1) if found else None
            break
    if not target:
        raise ValueError(f"EASI calculator template has no relationship {rid!r}")
    part = target.lstrip("/")
    return part if part.startswith("xl/") else f"xl/{part}"


def _repack(source: bytes, replacements: dict) -> bytes:
    """Rewrite the package with some parts replaced and the rest copied.

    ``copy.copy`` on each ``ZipInfo`` because ``writestr`` writes the CRC and
    sizes back into the object it is given. Copying also carries the 1980
    timestamps through, so the output is deterministic.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(source)) as zin, \
            zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zout:
        for info in zin.infolist():
            data = replacements.get(info.filename)
            if data is None:
                data = zin.read(info.filename)
            zout.writestr(copy.copy(info), data)
    return buf.getvalue()


# --- The completed workbook -------------------------------------------------------
def build_filled(result: dict, *, today: _dt.date | None = None) -> bytes:
    """The calculator with this screening typed into its entry cells.

    The workbook already recalculates on open (``fullCalcOnLoad``) and carries no
    cached results, so only the EASI Score part changes; every other part is
    copied byte for byte.
    """
    today = today or _dt.date.today()
    cells = entry_cells()
    entries, disclosures = entries_from_result(result)
    entries["site_date"] = _excel_serial(today)
    entries[NOTES_NAME] = notes_text(result, disclosures, today)
    values = {}
    for name, value in entries.items():
        if name not in cells or value is None or isinstance(value, bool):
            continue
        if isinstance(value, numbers.Real):
            if _number_text(value) is None:
                continue      # not finite: unknown, so the cell stays blank
        else:
            value = str(value) if name == NOTES_NAME else str(value).strip()
            if name == "in_category":     # the list's own spelling: 4A, not " 4a "
                value = value.upper().replace(" ", "")
            if not value:
                continue
        values[cells[name]] = value

    source = blank_bytes()
    with zipfile.ZipFile(io.BytesIO(source)) as zin:
        sheet_part = _sheet_part(zin, SHEET_NAME)
        sheet_xml = zin.read(sheet_part).decode("utf-8")
    filled = _fill_cells(sheet_xml, values, notes_ref=cells[NOTES_NAME])
    return _repack(source, {sheet_part: filled.encode("utf-8")})


def filled_filename(result: dict) -> str:
    """``easi-calculator-comid-<id>.xlsx`` (or NHDPlusID, or coordinates)."""
    from . import report          # local: report imports the plotting stack

    slug = report.site_slug(result)
    return f"easi-calculator-{slug}.xlsx" if slug else "easi-calculator.xlsx"
